### ISSUE TITLE
Limitation of 20 characters for package name

### ISSUE THREAD

**Issue by Applelo** [jsr-io/jsr#114]
Hi, really cool project but I am facing one problem to publish my package to JSR : the limitation of 20 characters and the fact my plugin name is `vite-plugin-browser-sync`. I think I will not be alone with all `vite-plugin-` prefix 😄 

<img width="586" alt="image" src="https://github.com/jsr-io/jsr/assets/7613286/637e50cf-b903-465d-8813-8679d90d038c">

Maybe increase a little bit? You don't need to go crazy like npm 😃

**Comment by lucacasonato** [comment]
Let's increase the limit to 32 chars. We need to keep the combined scope + package name at under around 55 chars to ensure that we don't overrun Windows file paths when the user's home directory is >= 45 chars.

**Comment by piranna** [comment]
> Let's increase the limit to 32 chars. We need to keep the combined scope + package name at under around 55 chars to ensure that we don't overrun Windows file paths when the user's home directory is >= 45 chars.

The actual limit seems to be [260 characters](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry), including device letter and final NUL character, being path itself up to 256 characters by default. Why to keep combined limit of scope + package name + home directory under 100 characters?

**Comment by lucacasonato** [comment]
Because we allow the file names in packages to be up to 155 chars (see https://jsr.io/docs/troubleshooting#invalidpath).

Ideally path to project + scope + package name + version + path in package is <= 256 :)

**Comment by piranna** [comment]
Ah, inside... Ok, make sense then (having Windows such limit, not so much).
