### ISSUE TITLE
Docs: GitHub sign in asks for “act on your behalf”

### ISSUE THREAD

**Issue by skybrian** [jsr-io/jsr#118]
I’m wary of allowing other websites to have excessive permissions on GitHub. Is there some way of making it possible to publish packages without the “act on your behalf” permission?

**Comment by marvinhagemeister** [comment]
Related issue in the official GitHub discussions https://github.com/orgs/community/discussions/37117 .

The tldr is that GitHub shows this phrasing whenever one has an app to authenticate via GitHub, even if 0 permissions are requested and the app doesn't act on behalf the user in any way.

**Comment by skybrian** [comment]
Thanks!

If this is just for logging in, a workaround might be to make an "OAuth App" rather than a "GitHub App." 

GitHub discourages it, but I don't know why. It seems to work?

**Comment by lucacasonato** [comment]
Using a an OAuth app prevents us from requesting more permissions in the future for new features we may want to add.

**Comment by ry** [comment]
This should be added to FAQ since it has come up a few times.
