### ISSUE TITLE
Symbols should be sorted in doc

### ISSUE THREAD

**Issue by ssssota** [jsr-io/jsr#126]
The order of the symbols in the document is flaky on every access.

e.g. *https://jsr.io/@vcltk/ast/doc/~/Declaration*

|typealias first|namespace first|
|--|--|
|![image](https://github.com/jsr-io/jsr/assets/15074382/b61c5eac-dbb6-4439-8a10-0ec8e5e0bb15)|![image](https://github.com/jsr-io/jsr/assets/15074382/6dbc6743-dee0-49cd-82f0-b60131fe3fb5)|

This issue may depend on [deno_doc](https://github.com/denoland/deno_doc/blob/bbdea9fa27994831b4ea82868ec0ba6c7d56fed5/src/html/symbols/mod.rs#L57).

**Comment by bartlomieju** [comment]
We are aware of the problem and @crowlKats is working on a fix.
