### ISSUE TITLE
Did you support JSON5?

### ISSUE THREAD

**Issue by dutscher** [jsr-io/jsr#127]
Hi there,
great that you get forward. 

I have a question because this project is new.
Will you implement support for [json5](https://json5.org/) and the comment function in json?

Nodejs closed this issue: https://github.com/nodejs/node/issues/40714
Npm will do when nodejs and js do something and locked the discussion: https://github.com/npm/feedback/discussions/56#discussioncomment-8591686

That is a usp for your project :)

Thanks for the attention.
Cheers

**Comment by bartlomieju** [comment]
JSON5 is not supported, but jsr support JSONC - you can use `deno.jsonc` or `jsr.jsonc` and put comments in the files :)

**Comment by lucacasonato** [comment]
Closing because the question is answered.
