### ISSUE TITLE
Support rendering markdown "alerts" syntax 

### ISSUE THREAD

**Issue by magurotuna** [jsr-io/jsr#132]
It would be great if we could add support for rendering "alerts" syntax that's available recently in GitHub: https://github.com/orgs/community/discussions/16925

An example that uses this syntax is [@badrap/valita](https://jsr.io/@badrap/valita). As shown in the screenshot below, this syntax is rendered with no decoration, which is okay but not ideal.

![Pasted_Image_2024_03_03_0_01](https://github.com/jsr-io/jsr/assets/23649474/542b0f4e-9569-4a6b-98c3-37ebab9ad20d)

To support this syntax, we need to fix markdown parsing logic performed in the backend API server, which intenally calls [deno_doc::html::jsdoc::markdown_to_html](https://docs.rs/deno_doc/latest/deno_doc/html/jsdoc/fn.markdown_to_html.html), and finally ending up with [comrak](https://docs.rs/comrak/latest/comrak/) crate as a markdown parser library. The problem is that this crate doesn't plan to support "alerts" syntax at least for the time being (see https://github.com/kivikakk/comrak/issues/352). We need to come up with another solution here.

**Comment by crowlKats** [comment]
Closing as this was implemented
