### ISSUE TITLE
Something rewrote my import to `from 'npm:lit@^2.2.7';` and now I can't build with `esbuild`

### ISSUE THREAD

**Issue by simonw** [jsr-io/jsr#139]
My original source code here: https://github.com/simonw/datasette-table/blob/0.1.0/datasette-table.js

```javascript
import {LitElement, html, css} from 'lit';
```
After I published it to `jsr.io` it was rewritten like this: https://jsr.io/@datasette/table/0.1.0/datasette-table.js

```javascript
import {LitElement, html, css} from 'npm:lit@^2.2.7';
```
But now when I try to install it and run it through `esbuild` I get an error:
```bash
mkdir /tmp/datasette-demo
cd /tmp/datasette-demo
npx jsr add @datasette/table
echo 'import * as mod from "jsr:@datasette/table";' > index.js
npx esbuild index.js --bundle --outfile=bundle.js
```
Error:
```
✘ [ERROR] Could not resolve "npm:lit@^2.2.7"

    node_modules/@datasette/table/datasette-table.js:1:36:
      1 │ import {LitElement, html, css} from 'npm:lit@^2.2.7';
        ╵                                     ~~~~~~~~~~~~~~~~

  You can mark the path "npm:lit@^2.2.7" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

1 error
```
I asked in Discord and `marvinh` said: https://discord.com/channels/684898665143206084/1203185670508515399/1213595537505521664

> Esbuild doesn't understand `npm:` or `jsr:` . That's a Deno only thing. So your source code should not have import specifiers with these prefixes anywhere. That said the lit error looks like a bug. That should've been transpiled away

More of my notes here: https://til.simonwillison.net/javascript/jsr-esbuild

**Comment by simonw** [comment]
Bill Mill found a workaround using [esbuild_deno_loader](https://github.com/lucacasonato/esbuild_deno_loader):

https://notes.billmill.org/programming/javascript/build_tools/using_esbuild_to_package_a_deno_package_for_the_browser.html

**Comment by dsherret** [comment]
The `jsr` tool should not be pulling in npm specifiers. That's a bug. The specifier at https://jsr.io/@datasette/table/0.1.0/datasette-table.js is correct, but the specifier in node_modules/@datasette/table/datasette-table.js is wrong. It should be "lit"

**Comment by lucacasonato** [comment]
The fix is in https://github.com/jsr-io/jsr/pull/172

**Comment by simonw** [comment]
Thanks, this works for me now! Notes here: https://til.simonwillison.net/javascript/jsr-esbuild#user-content-and-now-it-works

**Comment by marvinhagemeister** [comment]
Thanks for updating the blog post. Yeah it was just a bug on our end. Happy to see it resolved 👍
