### ISSUE TITLE
How to publish a package that requires shims for Node.js?

### ISSUE THREAD

**Issue by bradenmacdonald** [jsr-io/jsr#141]
I've published a package on JSR: https://jsr.io/@bradenmacdonald/s3-lite-client

But it's not currently usable in Node.js because it uses the Web Crypto and Web Streams APIs (i.e. expects `crypto` and `ReadableStream`/`TransformStream` etc. in the global namespace).

The thing is, I know that [dnt](https://github.com/denoland/dnt) can add these shims (though streams currently requires a `custom` shim). But I can't find any documentation or FAQ on the JSR website about how to tell JSR that it needs to add those shims for the npm transpiled version my package. Are they supposed to be auto-detected? Or is that not possible at the moment?

**Comment by marvinhagemeister** [comment]
Not possible at the moment. JSR doesn't shim anything.

**Comment by lucacasonato** [comment]
Node has both web crypto `crypto` and streams (`ReadableStream`/`TransformStream`) in global scope now.

You should not need those shims anymore :)

**Comment by wojpawlik** [comment]
I need to shim `Deno.noColor` for Node.js, but using `process.env` will cause an unnecessary permission prompt on Deno. It'd be nice if JSR could auto-inject https://github.com/denoland/node_shims into npm tarballs that need it.

Anyway, how to get JSR to emit `"bin"` in `package.json` for CLIs?

**Comment by bradenmacdonald** [comment]
> Node has both web crypto crypto and streams (ReadableStream/TransformStream) in global scope now.
>
> You should not need those shims anymore :)

TIL!
You're right, I was testing with Node 18. With Node 19+ it's working well 🎉 . I'm going to close this now since my original use case doesn't seem to be an issue anymore.
