### ISSUE TITLE
Better documentation of the jsr.json file & json schema

### ISSUE THREAD

**Issue by ghostdevv** [jsr-io/jsr#142]
I wasn't able to find a documentation page on the `jsr.json` file - let me know if I missed something! Additionally, it would be awesome to have a json schema for it so I can get intellisense in my editor.

I'm happy to send a PR if this is wanted!

**Comment by lucacasonato** [comment]
Yeah, there is no schema for it yet. It's a subset of the `deno.json` schema: https://github.com/denoland/deno/blob/main/cli/schemas/config-file.v1.json

Only these fields are valid in `jsr.json`:

- `name`
- `version`
- `exports`
- `include`
- `exclude`

A PR that adds the a schema would be great - ideally we can link it from the docs :)
