### ISSUE TITLE
Support rendering lowercase `readme.md`

### ISSUE THREAD

**Issue by omar-azmi** [jsr-io/jsr#143]
Currently, the homepage of a package only displays the readme file if it's named in all uppercase letters (i.e. `README.md` , `README.txt`, etc...).
I'm not sure if it's by choice, but since the file names are supposed to be case insensitive, I suppose it might be a good idea to allow case insensitive readme files to be displayed as well.

I think the code related to the selection of the displayed readme file is here: [`/api/src/ids.rs#L582`](https://github.com/jsr-io/jsr/blob/7e84263e1d399877695e9576c649fff26c340b41/api/src/ids.rs#L582) (but I could be completely wrong)

Changing the line from `&& name == "README"` to `&& name.to_uppercase() == "README"` might solve the issue.

**Comment by lucacasonato** [comment]
Yes, this is the right place. The correct fix is to replace:

https://github.com/jsr-io/jsr/blob/7e84263e1d399877695e9576c649fff26c340b41/api/src/ids.rs#L567

with

```
let path = std::path::PathBuf::from(self.lower.as_ref().unwrap_or(&self.path));
```

and then change `"README"` to `"readme"`.

This will get the normalized lowercased name from the `PackagePath`, and compare it to the lowercase `"readme"`.

**Comment by omar-azmi** [comment]
Awesome, I hope it gets integrated into upcoming patches.

Also, a big thanks to all in the Deno team for building all these incredible tools!
