### ISSUE TITLE
What if jsr goes down? (how to mirror?)

### ISSUE THREAD

**Issue by pi0** [jsr-io/jsr#144]
This had been always a worrying fact about npm that if the service goes down / interrupted or blocked, there would be a disaster without backup plan.

Many of FOSS package repositories have a mirroring mechanism. Would JSR be open to provi a protocol for mirroring meta + data?

**Comment by ry** [comment]
JSR is built with robustness in mind; even if the website and database encounter issues, code distribution remains unaffected thanks to direct delivery from storage buckets, ensuring reliability on par with GCP.

We're open to implementing a mirroring mechanism for additional redundancy of package sources. However, it's crucial to first establish a clear design. We welcome a detailed proposal outlining a potential implementation.

**Comment by lucacasonato** [comment]
I'll move this into #110 (underlying work necessary to enable mirroring).
