### ISSUE TITLE
Long versions occlude package name in "Recent updates"

### ISSUE THREAD

**Issue by ry** [jsr-io/jsr#145]
This package has a very long version.
https://jsr.io/@fedify/fedify@0.1.0-dev.20+c6eda9ec

Seems like it would be better to cut off the end of the version rather than package name.

<img width="376" alt="Screenshot 2024-03-03 at 8 29 27 AM" src="https://github.com/jsr-io/jsr/assets/80/8a097304-e79c-4091-8760-154948d02d19">

**Comment by marvinhagemeister** [comment]
Wondering if we should exclude pre-release versions entirely from this widget and only show non-pre-release versions.

**Comment by dahlia** [comment]
The author of \@fedify/fedify here.  It would be better to exclude pre-release versions at all from *Recent updates*.
