### ISSUE TITLE
Missing config file '/jsr.json' should include help about why

### ISSUE THREAD

**Issue by ghostdevv** [jsr-io/jsr#154]
Example output:

```bash
Publishing @ghost/kjua-revived@0.2.0 ...
error: Failed to publish @ghost/kjua-revived@0.2.0

Caused by:
    Failed to publish @ghost/kjua-revived at 0.2.0: missing config file '/jsr.json'
```

Not sure what's causing this as far as I am aware I haven't changed anything since I published last and the `jsr.json` exists.

**Comment by ghostdevv** [comment]
I get the same error locally and with the GitHub action

**Comment by lucacasonato** [comment]
Did you exclude the file? You can check with `--dry-run`?

**Comment by ghostdevv** [comment]
I've tried with the following `jsr.json` and it still lists no files to be published. If I comment out `exclude` it works

```json
"exports": {
    "./package.json": "./package.json",
    ".": "./src/kjua.ts"
},
"exclude": [
    "**"
],
"include": [
    "src/**",
    "README.md",
    "LICENSE",
    "jsr.json"
]
 ```

**Comment by lucacasonato** [comment]
There is currenly a bunch of bugs related to excludes and includes: https://github.com/denoland/deno/issues/22648

This probably comes from those. We're working on these.

**Comment by lucacasonato** [comment]
Let's improve the error message to include that maybe you excluded this file through `include` and `exclude`.

**Comment by cloydlau** [comment]
1. `include` does not exclude `.gitignore`
2. `include` does not exclude `"exclude": ["**"]`
3. Files not declared in the `include` should not be included
4. How about directly supporting the `files` field of `package.json`?

**Comment by ghostdevv** [comment]
I second @cloydlau that it would be nice to support the `files` field but if the [`exclude` and `include`](https://archive.ph/kof8a#ignoring-files) trick can be fixed I'm happy

**Comment by cloydlau** [comment]
It might be best approach if simply copy and paste the `files` field from the package.json file is good to go.
It will lower the cost of migrating from npm to JSR.
