### ISSUE TITLE
Support github markdown videos

### ISSUE THREAD

**Issue by littledivy** [jsr-io/jsr#160]
https://github.com/littledivy/deno_sdl2/blob/main/README.md

https://jsr.io/@divy/sdl2 

This is currently rendered as a link 
![image](https://github.com/jsr-io/jsr/assets/34997667/ddaa45ed-5310-4a0a-afd2-b1fd72ded8db)

**Comment by cu8code** [comment]
@lucacasonato bro would like to work on this not sure how to any recommendation would help

**Comment by cu8code** [comment]
it seems that I have to add some library like Video-JS, that can play this media format.

**Comment by lucacasonato** [comment]
@crowlKats Can you give some pointers?

**Comment by crowlKats** [comment]
I actually already opened a PR in deno_doc for this: https://github.com/denoland/deno_doc/pull/528
