### ISSUE TITLE
Shouldn't the project be named "TypeScript Registry"?

### ISSUE THREAD

**Issue by mike-lischke** [jsr-io/jsr#168]
I just found this project and, as a full-time TypeScript developer, I find it a very interesting approach. However, I was wondering why it is called "JavaScript Registry" since it is all about TypeScript?

**Comment by lucacasonato** [comment]
You can also publish JS to JSR. JSR supports TS as a native first class citizen, but this is still the JavaScript ecosystem (with JS runtimes, etc), so it is called JSR :)

**Comment by mike-lischke** [comment]
A pity you closed this issue so quickly. My hope was to have a meaningful discussion about the name. But on the other hand it's not that important and you already have the www domain etc. set up for JSR, so I didn't expect it to change. Just tried to understand the reasoning and why I should start using JSR at all.

**Comment by lucacasonato** [comment]
If you have other questions, feel free to ask. But we will not be changing the name :)
