### ISSUE TITLE
How do I remap JSR imports to local modules?

### ISSUE THREAD

**Issue by jollytoad** [jsr-io/jsr#175]
In my library that I've converted to JSR, I have a bunch of examples, some of which are even tested.

I want the examples to be a true reflection of usage, ie. imports from JSR, not relative, but I also want to be able to execute examples locally (whilst developing and testing) and remotely.

Given this [example](https://github.com/jollytoad/deno_http_fns/blob/main/examples/logging.ts
), based on deno.land https imports still...

```ts
import { intercept } from "https://deno.land/x/http_fns/lib/intercept.ts";
import { logging } from "https://deno.land/x/http_fns/lib/interceptor/logger.ts";

export default Deno.serve(intercept(
  () => new Response("Hello"),
  logging(),
));
```

I could run this example locally, by using the import map to remap the url locally...

```sh
deno run -A --import-map=examples/import_map.json examples/logging.ts
```

where `examples/import_map.json` is...

```json
{
  "imports": {
    "https://deno.land/x/http_fns/": "../"
  }
}
```

this could also run directly from deno.land:

```sh
deno run -A https://deno.land/x/http_fns/examples/logging.ts
```

or directly from GitHub:

```sh
deno run -A https://raw.githubusercontent.com/jollytoad/deno_http_fns/main/examples/logging.ts
```

This allows me to develop, and test these locally against my local modules, and also allow users to either do the same, or just run individual examples remotely without the faff of checking out the entire repo.
It also allows me to give real examples with realistic imports (ie. not relative ones), so a user could copy the example wholesale and adapt it.

As I convert to JSR, I'm struggling to work out how to handle this situtation cleanly.

If I change my example to reflect jsr usage:

```ts
import { intercept } from "@http/fns/intercept";
import { logging } from "@http/fns/interceptor/logger";
```

I can no longer remap these to the local modules.

I really like the rest of the JSR concept, but this is becoming a bit of a blocker for me to fully embrace it.

Also, I've found this ability to remap modules is vital in fixing of upstream bugs in dependencies, I can checkout a dependency locally, fix a bug or add a feature and test my code against it simply by remapping the module URLs. I can also progress my own project then without waiting for the fix to be applied and published upstream.

I really think JSR needs to address this to set itself apart from npm and avoid diminishing the advantages of import mapping in Deno.

**Comment by lucacasonato** [comment]
You can user `jsr:@http/fns` to refer to your package locally. If you are in a package with `name` set, we'll use the local copy (if the version constraint allows it) instead of using the copy from the registry.

So you can just add:

```ts
  "imports": {
    "@http/fns": "jsr:@http/fns"
  }
```

And everything will work as expected :)

**Comment by jollytoad** [comment]
Ok, I've converted all my examples now, and published a new version.

The LSP doesn't seem to be aware of this rule, it opens the remote version of an import rather than local, which would be useful.

It'd also be useful if `--watch` knew about this too and restarted when the imported module was updated locally.

**Comment by jollytoad** [comment]
Just try to determine if I could run remote examples, but getting this...

```sh
$ deno run -A https://jsr.io/@http/fns/0.6.1/examples/logging.ts
error: Importing a JSR package via an HTTPS URL is not implemented. Use a jsr: specifier instead for the time being.
```

I don't really want to export the examples, as they aren't really a consumable of the library.

Will this ever become possible?

**Comment by dsherret** [comment]
> Will this ever become possible?

Yes. It's just not implemented at the moment because there's some complications around it.

**Comment by lucacasonato** [comment]
> The LSP doesn't seem to be aware of this rule, it opens the remote version of an import rather than local, which would be useful.

Yeah, we're aware. Will open a separate bug for this on Deno :)

**Comment by jollytoad** [comment]
This satisfies the case of local module import within the same package, but what about importing from a different local jsr, ie.equivalent of `npm link` but not nearly as horrific ;)
