### ISSUE TITLE
[Feature Request] Add typings to npm package

### ISSUE THREAD

**Issue by angelnext** [jsr-io/jsr#180]
When installing as an npm package, if the file is a mod.ts, it will not automatically detect typings, so it should be added to package.json, like:

```json
{
  "types": "./mod.d.ts"
}
```

**Comment by marvinhagemeister** [comment]
The types are detected automatically for me when `"type": "module"` is set in `package.json`. Do you have that in your project?

**Comment by angelnext** [comment]
yep, tried with my neovim setup and a clean VSCode setuo

**Comment by lucacasonato** [comment]
Do you have a `tsconfig.json`?

**Comment by angelnext** [comment]
thanks, adding a tsconfig with these options does help, but, wouldn't it be nice if you could get those typings without a tsconfig file? just a vanilla javascript project with type: module should be enough

**Comment by bjesuiter** [comment]
How can i update my jsr package to get the new types-property in the generated package-json?

**Comment by lucacasonato** [comment]
We now provide a types property in the exports for all packages. You can just delete your lockfile and download a package to get the new manifest.

**Comment by bjesuiter** [comment]
thanks, i tried reinstalling but forgot to delete the lockfile, therefore it did not work :D
