### ISSUE TITLE
Documentation not being picked up

### ISSUE THREAD

**Issue by b3nten** [jsr-io/jsr#184]
Not exactly sure what's happening here. No docs are showing up for any of the modules including the entry point.

https://jsr.io/@build/scheduling

**Comment by lucacasonato** [comment]
Docs are showing up for entrypoints other than the root one:

https://jsr.io/@build/scheduling/doc/defer/~

But it looks like the root module doc is not being picked up.

**Comment by GavinMeierSonos** [comment]
@b3nten @lucacasonato Through some testing I noticed that the @module has to be the last line in the jsdoc comment. It doesn't list this in the normal jsdoc documentation but it does show this usage in the typedoc documentation.

**Comment by lucacasonato** [comment]
We'll fix this

**Comment by crowlKats** [comment]
as a general rule, for jsdoc tags, they need to be always after the main body of a jsdoc, since many tags are greedy.

on the note of `@group`, i have never seen it before, nor does it seem to be part of the jsdoc or tsdoc specs. what does it do? same as `@category`?
