### ISSUE TITLE
REPL - Could not find constraint in list of versions when library is not cached

### ISSUE THREAD

**Issue by retraigo** [jsr-io/jsr#191]
(Deno)

Steps to reproduce:
1. Cache a version of your JSR module.
2. Publish a new version.
3. Import the new version inside the REPL or a Jupyter notebook.

![image](https://github.com/jsr-io/jsr/assets/56877379/720453f9-e878-4fa5-b1ba-3b10456bf438)

There isn't a time frame within publishing of a new version for this issue to happen. It happens even days later as long as it hasn't been cached already.

I can cache it when using `deno run` or when using the command "Deno: Cache Dependencies". Only Jupyter and the REPL have this issue.

**Comment by dsherret** [comment]
What version of deno are you using?

**Comment by dsherret** [comment]
Oh, nevermind, just read:

> I can cache it when using deno run or when using the command "Deno: Cache Dependencies". Only Jupyter and the REPL have this issue.

**Comment by dsherret** [comment]
Seems I can't transfer this to the deno repo, but it's a deno issue and not really jsr.

**Comment by retraigo** [comment]
Should I close it here and reopen in the deno repo?

**Comment by retraigo** [comment]
Opened https://github.com/denoland/deno/issues/22748
