### ISSUE TITLE
Include and Exclude does not work correctly

### ISSUE THREAD

**Issue by ghostdevv** [jsr-io/jsr#194]
An example of this is that trying to recreate the `files` behaviour in `package.json` by excluding everything and including specific things doesn't work. The package tries to publish zero files.

<details>
<summary>Example config</summary>

```json
{
    "name": "@ghost/kjua-revived",
    "version": "0.2.0",
    "exports": {
        "./package.json": "./package.json",
        ".": "./src/kjua.ts"
    },
    "include": [
        "src/**",
        "README.md",
        "LICENSE",
        "jsr.json"
    ],
    "exclude": [
        "**"
    ]
}
```

</details>

<details>
<summary>Docs excerpt</summary>

https://archive.ph/kof8a#ignoring-files

![image](https://github.com/jsr-io/jsr/assets/47755378/c6968ed0-dbe9-4ec0-a425-d2ac03cedb40)

</details>

---

Related: [#22648](https://github.com/denoland/deno/issues/22648)

**Comment by ghostdevv** [comment]
Mostly creating this issue for tracking/visibility for others since it looks like that issue in Deno repo is the cause but there is no issue here for it :pray:

**Comment by lucacasonato** [comment]
Thanks - I'll also add a note to the docs.

**Comment by cloydlau** [comment]
I'm kinda stuck here. The file I want to publish is in the .gitignore, which prevents me from publishing. I'd like to know when will this fix be released, and how do I upgrade JSR?

**Comment by ghostdevv** [comment]
@cloydlau `npx jsr@latest` should help!

**Comment by cloydlau** [comment]
@ghostdevv Thanks, I've upgraded jsr to v0.11.0 using this command, but still the about-to-publish file list is empty when I run `npx jsr publish --dry-run`.

**Comment by dsherret** [comment]
The docs are still incorrect. There is an open PR here: https://github.com/jsr-io/jsr/pull/238

Change the config to this (unfortunately it needs to be nested under the "publish" config for the time being, but in the future that will be collapsed down):

```json
{
    "name": "@ghost/kjua-revived",
    "version": "0.2.0",
    "exports": {
        "./package.json": "./package.json",
        ".": "./src/kjua.ts"
    },
    "publish": {
      "include": [
          "src/**",
          "README.md",
          "LICENSE",
          "jsr.json"
      ]
    }
}
```

**Comment by cloydlau** [comment]
I tried the nested "publish", the about-to-publish file list is not empty now, but the directories or files listed in the .gitignore are still missing even if they are explicitly declared in `publish.include`.
