### ISSUE TITLE
wrong auto-generated import statements

### ISSUE THREAD

**Issue by ry** [jsr-io/jsr#197]
default exports are not handled correctly: https://jsr.io/@ry/one-true-date@0.1.9/doc/~/default displays
```js
import { default } from "@ry/one-true-date";
```
should be 
```js
import x from "@ry/one-true-date";
```

Also inside an export/module the import statement is not correct. for example https://jsr.io/@ry/one-true-date@0.1.9/doc/export2/~/thing2 displays
```js
import { thing2 } from "@ry/one-true-date";
```
but should be 
```js
import { thing2 } from "@ry/one-true-date/export2";
```

**Comment by crowlKats** [comment]
Partial duplicate of https://github.com/jsr-io/jsr/issues/125 and https://github.com/jsr-io/jsr/issues/153
