### ISSUE TITLE
On attempting to publish a duplicate version from the CLI, browser is opened to a page that never closes

### ISSUE THREAD

**Issue by kwhinnery** [jsr-io/jsr#200]
I tried to publish a package version that already existed, but was brought to this browser page which never closed. I went back to the terminal eventually, but it would be nice to not sit on this page as watch it do nothing if `deno publish` fails

![image](https://github.com/jsr-io/jsr/assets/29193/8d27b7d1-9aef-480f-a1f2-2b5e165262b0)

**Comment by marvinhagemeister** [comment]
We should make the "Waiting a long time? Check your terminal for more detailed status." visually more distinct. It's quite easy to miss.
