### ISSUE TITLE
Specifying dynamic import dependencies

### ISSUE THREAD

**Issue by kitsonk** [jsr-io/jsr#201]
To provide compatibility under Bun and Node.js for one of my projects, I need to dynamically import a polyfill in those environments and I can't seem to get the publish to identify that as a dependency.

I have tried adding it to the import map and even included a `package.json` as part of the project, and while the dependency is resolved locally with the Deno CLI, it is not detected on publish, and therefore on consumption the dependency is not there.

There should be a way to specify dependencies that does not get elided upon "incorrect" static analysis.

**Comment by lucacasonato** [comment]
How are you including it?

`await import("specifier")` should be working

**Comment by kitsonk** [comment]
It is in a [conditional block](https://github.com/oakserver/acorn/blob/8a615f1325b32088c742af0cd658041c3592f30f/router.ts#L62-L64):

```ts
if (!("URLPattern" in globalThis)) {
  await import("urlpattern-polyfill");
}
```

I tried with `npm:urlpattern-polyfill`, adding to the import map in `deno.json` and adding to the `package.json` and in each case they either don't get detected or elided.

The version [0.5.1-alpha.4](https://jsr.io/@oak/acorn@0.5.1-alpha.4), [0.5.1-alpha.3](https://jsr.io/@oak/acorn@0.5.1-alpha.3) and [0.5.1-alpha.2](https://jsr.io/@oak/acorn@0.5.1-alpha.2) all contain the various forms that don't include the dependency when consumed via Node.js or Bun.

**Comment by lucacasonato** [comment]
Gee, yeah that looks like a bug. Will fix tomorrow
