### ISSUE TITLE
Publish from Github organization

### ISSUE THREAD

**Issue by piranna** [jsr-io/jsr#202]
At https://jsr.io/docs/publishing-packages#publishing-from-github-actions, it explains how to publish from Github Actions, but when trying to link my packages with my Github organization, it's not possible, only with my personal account. How can I link the package to the repo of my Github organization? Is it possible to do it too with private packages (and repos)?

**Comment by roj1512** [comment]
I’m publishing a package from an org, and I don’t have any issues. I don’t think the docs directly state that its guide is only for user accounts.

> How can I link the package to the repo of my Github organization?

Just as you would do it with a repo in your user account. Either manually or via a workflow.

> Is it possible to do it too with private packages (and repos)?

I don’t know what you specifically mean by “with private packages,” but yes, you should be able to publish from GitHub Actions even if your repository is private.

**Comment by lucacasonato** [comment]
> it explains how to publish from Github Actions, but when trying to link my packages with my Github organization, it's not possible, only with my personal account

What error are you encountering? You must be an admin of the org you are linking

**Comment by roj1512** [comment]
What is pre-filled with your user account? Mind sharing some screenshots?

**Comment by piranna** [comment]
![Screenshot_20240306_111735_Chrome](https://github.com/jsr-io/jsr/assets/532414/b30d300b-d477-4e54-ac7c-b8a0b3c134cc)

Ok, finally i got It working, that "piranna" at the bottom looks like hardcoded, when in fact it's a prefilled text field. It would be better for UX that's a dropdown filled with all organizations where Usera has permissions, the same as happens in other sites. An auto-complete dropdown for the package name would be nice too

**Comment by lucacasonato** [comment]
Closing this for now, we're tracking the auto-completion behaviour in https://github.com/jsr-io/jsr/issues/23.
