### ISSUE TITLE
adding main to package.json

### ISSUE THREAD

**Issue by developedbyant** [jsr-io/jsr#204]
Add main to generated package.json to avoid typescript errors.
TypeScript error Cannot find module '@name/name' or its corresponding type declarations.
{
  "main": "./mod.js",
  "exports": {
    ".": "./mod.js"
  }
}

**Comment by marvinhagemeister** [comment]
Does adding `"type": "module"` to your project's `package.json` where you're trying to use a JSR package help?

**Comment by lucacasonato** [comment]
You should change your `tsconfig.json` to use either `"module": "nodenext"` or `"module": "bundler"`. All other module resolution modes in TypeScript do not respect `exports`.
