### ISSUE TITLE
JavaScript packages..?

### ISSUE THREAD

**Issue by osher** [jsr-io/jsr#206]
In your blog you say you are targeting JavaScript, however, on the other hand - you say you support TypeScript First.

I would not like to write my packages in TypeScript, but am providing a `types.d.ts`  and the rest of the docs for my users.

Is JSR for me, or it should have been named TSR?

**Comment by marvinhagemeister** [comment]
JSR is for you. Uploading `.js` files works too.

**Comment by roj1512** [comment]
@marvinhagemeister You might have incorrectly understood them. Apparently, they already know that he can publish `.js` files, too, but they asked if they could use a `.d.ts` to annotate its types.

**Comment by roj1512** [comment]
@marvinhagemeister You might have incorrectly understood them. Apparently, they already know that they can publish `.js` files, too, but they asked if they could use a `.d.ts` to annotate its types.

**Comment by marvinhagemeister** [comment]
> @marvinhagemeister You might have incorrectly understood them. Apparently, they already know that they can publish .js files, too, but they asked if they could use a .d.ts to annotate its types.

Yes, they can do that.

**Comment by roj1512** [comment]
Cool! Didn’t know this myself.
