### ISSUE TITLE
Typescript can't find type definitions of published package

### ISSUE THREAD

**Issue by alexgleason** [jsr-io/jsr#216]
In my JSR package I published, I specified `./mod.ts` as the export. This generates a file called `mod.js` and `mod.d.ts`. However, `mod.d.ts` is never actually used, so I get this error when I try to use the package in a Node/Yarn/Vite project:

![Screenshot from 2024-03-06 15-39-04](https://github.com/jsr-io/jsr/assets/3639540/bc12add8-2633-406a-bf5e-afbb5cfd34d7)

Importing it with `/mod` at the end works fine:

![image](https://github.com/jsr-io/jsr/assets/3639540/4efa04ad-c90f-4a36-b157-60ea482db2d6)

The code also works at runtime. It's just the types.

I think the `package.json` generated by JSR is missing a "types" property. It should point to `mod.d.ts` in this case.

![image](https://github.com/jsr-io/jsr/assets/3639540/72417918-7ed6-403e-ab82-f41f409c6973)

**Comment by alexgleason** [comment]
I was able to fix it in my project like this:

```diff
-     "moduleResolution": "node",
+     "moduleResolution": "Bundler",
```

But I still think JSR should add an explicit `"types": "./mod.d.ts"` to the generated package.json so it works in more cases.

**Comment by glebbash** [comment]
+1

All libraries I am trying to use from jsr in Node.js seem to have this problem. @lucacasonato this is not a feature request this is definitely a bug from the point of users of the libraries.

**Comment by alexgleason** [comment]
I think if you're using JSR, `moduleResolution: bundler` is the correct setting for your project

(Also, I realized afterwards this is a dupe of https://github.com/jsr-io/jsr/issues/180, but this ticket got triaged so I didn't close it)

**Comment by glebbash** [comment]
In my project which runs on both Node.js and Deno there are no tsconfig or jsconfig files. Type-checking is done via default `tsc` with `// @ts-check` comments. I had to switch to importing npm packages relying on Deno's compat layer instead of jsr to solve the type checking issue.

I don't think it's a good idea to leave defaults broken and it's not an option to have TypeScript default to `moduleResolution: "bundler"`  without configuration.

It would be beneficial to update `package.json` to make jsr work out of the box for Node.js.

**Comment by zephraph** [comment]
Just to pitch in here, changing the `moduleResolution` can be fairly disruptive on some projects. I don't believe adding a `types` entry in the package.json is nearly as disruptive. Is there some deeper complexity that makes that non-attractive?

**Comment by riderx** [comment]
I still have the issue when i import : https://jsr.io/@bradenmacdonald/s3-lite-client
what are we supposed to do?
