### ISSUE TITLE
404 immediately after hitting "publish" package when not an admin of a scope

### ISSUE THREAD

**Issue by lambtron** [jsr-io/jsr#222]
repro steps:
- on https://jsr.io/new, i selected `@deno` as my scope and `subhosting` as package name
- i click "publish"
- i see this 404 page

![image](https://github.com/jsr-io/jsr/assets/1080190/2dfedb12-a638-4ee4-8a40-e410373b9b0e)

link also still goes to 404
https://jsr.io/@deno/subhosting/publish

**Comment by dsherret** [comment]
The key point here is Andy's user was not an admin of the scope.
