### ISSUE TITLE
Failed to publish: missing config file '/deno.json'

### ISSUE THREAD

**Issue by garretmh** [jsr-io/jsr#224]
When attempting to run `deno publish` on a simple small package I receive this error message:

> Failed to publish @garretmh/nullish at 0.0.1: missing config file '/deno.json', is it perhaps excluded from publishing?

I can't figure out why it believes the deno.json file is missing. It's pulling the package name and version in the error message from the file and I am not using include or exclude.

The deno.json file content is this:

```json
{
  "name": "@garretmh/nullish",
  "version": "0.0.1",
  "exports": {
    ".": "./mod.ts",
    "./fp": "./fp/mod.ts"
  }
}
```

Full package source is here: https://github.com/garretmh/nullish

**Comment by lucacasonato** [comment]
Is `deno.json` listed in the files being uploaded (you can see this list with `deno publish --dry-run`

**Comment by garretmh** [comment]
That question helped figure out what happened. No files were listed when I ran `deno publish --dry-run`. I realized there was a .gitignore file in my home directory setup in a way that the entire directory was being ignored. This has never been an issue in other projects or with other tools but `deno publish` seems to respect that file, so I altered it an am now able to publish. Thank you.

**Comment by lucacasonato** [comment]
Great - there is a CLI issue to give an early warning when this happens: https://github.com/denoland/deno/issues/22657
