### ISSUE TITLE
website awful time to interactive

### ISSUE THREAD

**Issue by steven89** [jsr-io/jsr#225]
The particule effect is blocking the main thread and making the page non-interactive for almost 10 seconds on first load

<img width="576" alt="Screenshot 2024-03-07 at 11 17 17 AM" src="https://github.com/jsr-io/jsr/assets/609271/88787b40-f209-4058-a4ad-d9caae48a0f2">

Please consider removing this effect

**Comment by lucacasonato** [comment]
What device are you on? Do you mind running a performance profile in the DevTools "Performance" tab, and then exporting it so I can take a look?

Thanks!

**Comment by steven89** [comment]
I'm on macos 14.3 M2 chip. Browser engine is Chrome 122.
[Trace-20240307T121539.json](https://github.com/jsr-io/jsr/files/14523225/Trace-20240307T121539.json)

As a note, this happens on every first page load in a new tab, reloading does not have this issue

**Comment by lucacasonato** [comment]
@josh-collinsworth Can you take a look?

**Comment by josh-collinsworth** [comment]
@steven89 I've run that same Lighthouse test a few times now, and I can't replicate that result at all. I get an average total blocking time of only about 50ms. I'm also on an M2 Mac, on Chrome 122. On top of that, the particle effect is deferred; it shouldn't try to parse or render until the page is already loaded.

I'm not on MacOS 14.3 quite yet, so I suppose that could be related. But from what I can tell, at least, the result reported here is not at all consistent with what I'm seeing.

Any chance it might be extensions?

<img width="830" alt="image" src="https://github.com/jsr-io/jsr/assets/22334764/d62375a3-4cfe-4d89-8f83-914366bf2356">

<img width="823" alt="image" src="https://github.com/jsr-io/jsr/assets/22334764/49d3e0ef-3ebf-4732-9f0c-56e9d158b47f">

**Comment by steven89** [comment]
Disabling extensions didn't help.

I tested on other browsers and can't replicate the issue, even on other chromium based ones.

The issues occurs only in Vivaldi (6.6.3271.48) it seems. I tried disabling the built-in tacker & ad block still no change.
I'm not sure which exact version of Chromium 122 is running under the hood
From Brave 1.63.169 Chromium: 122.0.6261.111 the issue does not appear.

So i'd guess it's either the browser specific or the exact chromium version that has some problems.

I tested the website locally and found the culprit (turns out it's not JS)
https://github.com/jsr-io/jsr/blob/main/frontend/islands/HomepageHero.tsx#L165
```diff
<div
  class="text-2xl text-balance leading-[1.1] sm:text-3xl md:text-3xl lg:text-4xl opsize-normal md:opsize-sm text-center -mt-5 md:-mt-6 max-w-[20em]"
- style="text-shadow: 0 0 2em white, 0 0 1em white, 0 0 0.5em white, 0 0 0.25em white, 0 0 3em white, 0 0 0.5em white;"
```

Removing this line fixes the issue and brings the lighthouse score to 99.

**Comment by josh-collinsworth** [comment]
Weeeeeird! Wow, what a rabbit hole.

So safe to say this must be either browser- or Chromium version-specific, then? If so, I think it's probably safe to close the issue.

**Comment by gBasil** [comment]
I'm another one of the edge-case users with a similar setup (Vivaldi on an Apple Silicon chip). I've had to set up a uBlock Origin filter to remove the canvas, because it makes the site unusable for about 10 seconds once I load it.

**Comment by josh-collinsworth** [comment]
Are you sure it's the canvas? The previously reported issue turned out to be due to the rendering of the text shadow.

**Comment by gBasil** [comment]
I'm honestly not sure, but upon looking at it again, it seems like it isn't. I added a uBlock Origin rule to remove the text shadow, but that didn't seem to help:
```
jsr.io##.sr-only ~ div:style(text-shadow: none !important;)
```
I was thinking that it could potentially be the logo animation, but blocking that also doesn't seem to fix it. Blocking all three (canvas, logo, text shadow) *also* doesn't seem to help.
