### ISSUE TITLE
Publishing deno std to local JSR fails

### ISSUE THREAD

**Issue by jollytoad** [jsr-io/jsr#226]
I've setup a local JSR as instructed, and attempt to publish deno std to it as instructed, but some packages fail, starting with `@std/expect`...

```
error: Failed to publish @std/expect@0.218.2

Caused by:
    Failed to publish @std/expect at 0.218.2: failed to build module graph: Module not found "file:///_custom_equality_tester.ts".
```

I tried to remove this from the `workspaces`, and tried again only for another package to fail...

```
error: Failed to publish @std/testing@0.218.2

Caused by:
    Failed to publish @std/testing at 0.218.2: failed to build module graph: Module not found "file:///_test_suite.ts".
```

I can't see why this would happen, there doesn't appear to be any obvious problem with the code itself in those packages!

I've also raised this in deno_std... https://github.com/denoland/deno_std/issues/4448

**Comment by ry** [comment]
You need to first run this script to adjust the imports for JSR
https://github.com/denoland/deno_std/blob/main/_tools/convert_to_workspace.ts

In the future we’ll be integrating these changes into std.

**Comment by jollytoad** [comment]
I had already run this, as described in the docs.
