### ISSUE TITLE
Title overflow in symbols page

### ISSUE THREAD

**Issue by mary-ext** [jsr-io/jsr#254]
https://jsr.io/@mary/bluesky-client/doc/atp-schema/~/ComAtprotoSyncRequestCrawl.Input

<img width=240 src=https://github.com/jsr-io/jsr/assets/148872143/cb606782-7c1b-46ef-81ae-ec69cde18694>

**Comment by furkankly** [comment]
https://github.com/denoland/deno_doc/pull/540 should fix this.

**Comment by crowlKats** [comment]
Closing as it has been addressed.
