### ISSUE TITLE
UX: `align="center"` only working on headings.

### ISSUE THREAD

**Issue by marvinhagemeister** [jsr-io/jsr#265]
See https://jsr.io/@trpc/server

<img width="833" alt="Screenshot 2024-03-11 at 13 52 41" src="https://github.com/jsr-io/jsr/assets/1062408/f2ac2051-c958-4874-80e6-38518ea5ffbc">

vs npm:

<img width="855" alt="Screenshot 2024-03-08 at 10 35 51" src="https://github.com/jsr-io/jsr/assets/1062408/6d44adb9-2d3a-4565-9c00-778a3ab0943e">

**Comment by furkankly** [comment]
[This PR](https://github.com/denoland/deno_doc/pull/527) should fix this.

**Comment by lucacasonato** [comment]
Fixed by #527
