### ISSUE TITLE
Style GitHub Actions security settings

### ISSUE THREAD

**Issue by donjo** [jsr-io/jsr#27]
<img width="946" alt="Screenshot 2024-02-28 at 10 52 05 AM" src="https://github.com/jsr-io/jsr/assets/776987/0dc09515-ffc4-4a5c-bbef-ad177e04bbab">

With our recent color updates there isn't much distinction between the security mode that is selected vs the one that isn't selected. This should be updated so the selected one is more clearly selected and the un-selected one is more clearly not selected (but selectable)

**Comment by alectrocute** [comment]
Resolved in https://github.com/jsr-io/jsr/pull/117, this can be closed.
