### ISSUE TITLE
[ Feature ] Allow specifying what file to use as config

### ISSUE THREAD

**Issue by PhoneDroid** [jsr-io/jsr#286]
I have both a `jsr.json` and a `deno.json` file as I thought   
I could have both at the same time to keep the registry stuff   
separate from the rest.

However it seems the `npx jsr publish` command goes for the  
`deno.json` config instead, ignoring the `jsr.json` config  
entirely and I can't seem to find any way of overriding it.

Why not allow the user to override the used config explcitly with a parameter?

**Comment by lucacasonato** [comment]
You can use the `--config` flag to override the config flag to use.
