### ISSUE TITLE
jsr.io search fails to find users and packages

### ISSUE THREAD

**Issue by jacoborus** [jsr-io/jsr#294]
jsr.io does not show any result when I search for my username or packages:

- https://jsr.io/packages?search=jacoborus
- https://jsr.io/packages?search=estilo
- https://jsr.io/packages?search=hexterm

but they are published: https://jsr.io/@jacoborus

**Comment by Marcisbee** [comment]
Same thing here:
- https://jsr.io/packages?search=nanolex (is found, published 3 weeks ago)
- https://jsr.io/packages?search=exome (not found , published 3 days ago - https://jsr.io/@exome/exome)

**Comment by lucacasonato** [comment]
Looks to be an issue with Orama right now - they are taking a look. cc @micheleriva

**Comment by micheleriva** [comment]
That should be solved now!
