### ISSUE TITLE
Line numbers displayed incorrectly in Firefox

### ISSUE THREAD

**Issue by jackfiszr** [jsr-io/jsr#303]
![Screenshot 2024-03-19 at 09-13-09 @divy_tree - JSR-20240319-091710661.png](https://github.com/jsr-io/jsr/assets/7147395/ee9af0c6-975b-41d6-bfdd-dfb92fc79b59)

**Comment by lucacasonato** [comment]
My colleauge @dsherret was also not able to reproduce on Windows. Let's close and see if someone else reports this

**Comment by dsherret** [comment]
Was fine on Windows 11, Firefox 124.0.1.
