### ISSUE TITLE
use pnpm dlx jsr install to install all dependency packages, it fails to install successfully.

### ISSUE THREAD

**Issue by PoliWen** [jsr-io/jsr#304]
When I use “pnpm dlx jsr install“ to install all jsr packages listed in the package.json, it fails to install successfully.
My package.json includes the following dependency information.
``` javascript
// package.json
{
   "dependencies": {
      "@luca/cases": "npm:@jsr/luca__cases@^1.0.0",
      "@wen/utils": "npm:@jsr/wen__utils@^0.0.2"
    }
}
```
I need to use pnpm dlx jsr install @luca/cases @wen/utils, manually writing all package names, in order to install successfully. Why can't it directly read the package information from package.json and automatically install all of them?

**Comment by marvinhagemeister** [comment]
In that case running `pnpm i` should be enough. We could change the JSR tool to automatically run that under the hood when no package arguments are passed to it.

**Comment by PoliWen** [comment]
Thank you for your prompt response! I'm accustomed to simply running 'pnpm i' when using pnpm, so I hope JSR can also support automatic installation without passing parameters. Of course, executing 'pnpm i' directly is also an option.

**Comment by marvinhagemeister** [comment]
@PoliWen you can run `pnpm i` with JSR as well. The `pnpm dlx jsr` only adds the alias to the `package.json` and sets up `.npmrc`, but after that it simply calls `pnpm i <packages>` under the hood. Opened #67 that calls `pnpm i` when no package arguments are passed.

**Comment by PoliWen** [comment]
@marvinhagemeister Thank you very much, that's great, I admire your speed in handling questions.
