### ISSUE TITLE
When a pnpm-workspace.yaml file exists in the root directory, all JSR commands become invalid.

### ISSUE THREAD

**Issue by PoliWen** [jsr-io/jsr#306]
When I use pnpm's monorepo to organize projects, as long as there is a pnpm-workspace.yaml file in the root directory, all commands of JSR are invalid.
My project is organized as follows, and I want to use pnpm's monorepo to manage it. When I execute pnpm dlx jsr add @luca/cases in the playground folder, the command fails to execute successfully.
![image](https://github.com/jsr-io/jsr/assets/28656609/7c397b02-9af4-4b3e-a175-1133e2746380)
When I remove pnpm-workspace.yaml, I can execute the command successfully.

**Comment by PoliWen** [comment]
The JSR does not currently support the Monorepo package management format. Is there a detail I'm missing that might change this? Are there plans to support Monorepo in the future?

**Comment by marvinhagemeister** [comment]
Do you have a sample repo or something where we can reproduce the error?

**Comment by marvinhagemeister** [comment]
No worries, all good. Happy to hear that it was resolved 👍
