### ISSUE TITLE
Browse Packages page lists modules multiple times between pages.

### ISSUE THREAD

**Issue by BlackAsLight** [jsr-io/jsr#314]
As the title says, you can see many modules listed many types when flicking through the pages.![image](https://github.com/jsr-io/jsr/assets/44320105/0600e372-67db-4a85-96d0-142eeac7cfb8)![image](https://github.com/jsr-io/jsr/assets/44320105/7964426e-1c99-4fa5-a28b-cc5152c47996)![image](https://github.com/jsr-io/jsr/assets/44320105/6885278a-f9da-4f93-af86-c6a89887786c)![image](https://github.com/jsr-io/jsr/assets/44320105/dc832cf2-b46f-448f-a27d-23bb3b2f7d6b)![image](https://github.com/jsr-io/jsr/assets/44320105/cb2b36e2-da1f-4966-9077-d5d6d4a67f1c)

**Comment by marvinhagemeister** [comment]
Sounds like the same issue as https://github.com/jsr-io/jsr/issues/309
