### ISSUE TITLE
Does it support private deployment?

### ISSUE THREAD

**Issue by PoliWen** [jsr-io/jsr#321]
Our team has discussed whether it's suitable to introduce JSR into our project. Considering one issue, when there are internal packages that we don't want to publish publicly, does JSR support private deployment? We know that npm supports private deployment. Will JSR consider supporting private deployment in the future?

**Comment by marvinhagemeister** [comment]
No, at the moment JSR doesn't support private packages. All packages are public. We have an existing issue for that already. Let's continue the discussion in https://github.com/jsr-io/jsr/issues/203
