### ISSUE TITLE
how to create Web Workers from a JSR package

### ISSUE THREAD

**Issue by dbushell** [jsr-io/jsr#322]
I'm trying to create a [Worker](https://docs.deno.com/runtime/manual/runtime/workers) in a JSR package (for Deno).

```javascript
const worker = new Worker(import.meta.resolve('./worker.ts'), {
  type: 'module'
});
```

Where `worker.ts` is part of the package alongside this script.

I get the error:

```
error: Uncaught (in worker "") Importing a JSR package via an HTTPS URL is not implemented. Use a jsr: specifier instead for the time being.
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:204:19)
    at eventLoopTick (ext:core/01_core.js:169:7)
```

I've also tried `new URL('./worker.ts', import.meta.url)` — both work locally, but error if imported from JSR.

I tried just `./worker.ts` but this is invalid.

```
Uncaught (in promise) URIError: invalid URL: relative URL without a base: relative URL without a base
```

If the Worker constructor expects a non-relative `URL` and JSR doesn't allow HTTP imports, what is the recommended solution?

Seems like this API can't be used.

## Work around...

I've managed to cheat the system by bundling the Worker code and fetching it into a Blob:

```javascript
fetch(import.meta.resolve('./worker.bundle.ts')).then(
  async (response) => {
    const text = await response.text();
    const blob = new Blob([text], {type: 'application/typescript'});
    const url = URL.createObjectURL(blob);
    const worker = new Worker(url, {
      type: 'module'
    });
  }
);
 ```

This seems like a silly solution... am I missing something obvious?

**Comment by dsherret** [comment]
It's just not implemented yet. See the error message.

> Importing a JSR package via an HTTPS URL is not implemented. Use a jsr: specifier instead for the time being.

**Comment by Hexagon** [comment]
How far away is this? Just migrated https://jsr.io/@pup/pup from deno.land/x to jsr, and found out that the load balancer (which is using web worker) no longer works.

**Comment by dsherret** [comment]
I'm planning on working on it next week. Got delayed by some other stuff.
