### ISSUE TITLE
packageless modules

### ISSUE THREAD

**Issue by mfulton26** [jsr-io/jsr#327]
Are packages necessary? Some packages on NPM change regularly while most of their files (JS modules) do not.

I wonder if versioning would be better done at the module level. I haven't fully thought that through yet but I'm interested to learn if others can point out blocking reasons as to why modules can't be versioned, published, and consumed directly.

The local path of a module can be used to derive its published path. The version can be encoded in the path and/or in JSDoc tags decorating the `@module`. Local modules that are imported directly or indirectly from a published module wouldn't necessarily need to be versioned themselves although they could be. Only modules published could be intended for importing by consumers.

Maybe this wouldn't be a goal of JSR. Reasons might be that currently the ecosystem is too package centric to get away from them at the moment but long term I feel like a module registry could be simpler for publishing and consuming.

**Comment by mfulton26** [comment]
Thank you for the thorough reply there @marvinhagemeister. I very much appreciate it.

I was thinking that most modules would be ignored except for ones that the publisher includes some specific JSDoc. e.g. Modules that are intended to be main entry points could include a `@module` JSDoc with `@access public` or some other way opting into being a main entry point.

I think that would address most of the "packages provide explicit encapsulation and therefor tooling and developer experiences" concerns but perhaps not all.

Your point about tooling needing to parse the JS to extract information could be mitigating by the registry storing a "package"-like meta-data file with all the information that a `jr.json` needs but programmatically derived during, e.g., publishing. i.e. Internally a "packageless" registry could still have metadata (possibly even still model it as a "package" internally) but publishers and consumers would really only need to concern themselves with main-entry-point-modules.

A main-entry-point-module-registry would have "boundaries". Semantic versioning does seem very important, I agree there. I think that can be declared in JSON or encoded in a URL though (maybe I'm missing something there).

I want to give this some more thought. Thank you again for your reply. 👍🏻

**Comment by lucacasonato** [comment]
I am going to close this for now because we will not be implementing this right now for the reasons @marvinhagemeister described.
