### ISSUE TITLE
glob in `publish.include` has a lower priority than gitignored directory

### ISSUE THREAD

**Issue by cloydlau** [jsr-io/jsr#328]
The directories or files listed in the `.gitignore` are missing even if they are explicitly declared in `publish.include`.

According to the document:

> jsr publish will ignore files that are listed in a .gitignore file in the root of your package. Additionally, you can specify the exclude and include fields in your jsr.json / deno.json file to ignore or include specific files.

**Comment by lucacasonato** [comment]
@cloydlau do you have an example that reproduces this behaviour.

**Comment by cloydlau** [comment]
1. clone https://github.com/cloydlau/json-editor-vue.git
2. `pnpm i`
3. `pnpm build`
4. `npx jsr publish --dry-run --allow-dirty`
5. `dist/**` is listed in `publish.include`, but missing from the files that are about to be published

**Comment by lucacasonato** [comment]
I think this is intentional, and you probably have to add an `"exclude": [ "!dist/**" ]` (ie do not exclude dist/).

@dsherret can you confirm?

If that's right, this just needs a docs update.

**Comment by cloydlau** [comment]
`"include": ["dist"]` works, thanks.
