### ISSUE TITLE
dpx doesn't find module

### ISSUE THREAD

**Issue by rohrig** [jsr-io/jsr#331]
Hey 👋 , 

Firstly, I want to let you all know that I appreciate what you're building and I find it super cool 😎 

Okay what's going on? 

I want to run a command using dpx. I created the command and published it to jsr. But dpx can't find it. 

```bash
dpx @jurassicjs/create-monodeno
```

<img width="775" alt="image" src="https://github.com/jsr-io/jsr/assets/45824492/2bf25d9c-7bee-408b-90b7-719afdb739af">

---
When the first try failed I uploaded directly to deno.land/x

Now I could run the command, but . . .

Another issue discovered during this process it that paths aren't correctly resolved when running dpx in conjunction with jsr packages. 

If you run . . .

```bash
dpx monodeno@0.0.2 
```
you get . . .
<img width="799" alt="image" src="https://github.com/jsr-io/jsr/assets/45824492/8c0c2b3f-f1f5-484f-92cc-be19091f66f8">

I would love to help with these efforts in any small way I can. 

perhaps worth noting, using full paths allow me to run the command without issue. (for anyone looking for a temporary  solution to this issue)
```bash
dpx monodeno@0.0.3
```

so instead of:
<img width="569" alt="image" src="https://github.com/jsr-io/jsr/assets/45824492/a796247c-ca65-4d01-be57-cd2f8faa1972">

use:
<img width="834" alt="image" src="https://github.com/jsr-io/jsr/assets/45824492/82b8073d-3f9d-4ef3-a09d-461de046512a">

All the best,
Rick

**Comment by marvinhagemeister** [comment]
This is not an issue with JSR, but with the `dpx` tool. It seems like it doesn't support JSR specifiers. Note that the `denorg` organization under which their repository resides is not connected to Deno Land Inc. in any shape or form. The `dpx` tool seems to be a community project written by volunteers. If you [file an issue there](https://github.com/denorg/dpx), they might be able to help you.

**Comment by rohrig** [comment]
Got it @marvinhagemeister, thanks for the reply 

aside from dpx, what would be the proper way to execute this command which lives in the jsr registry? I tried a few different ways . . .

<img width="1049" alt="image" src="https://github.com/jsr-io/jsr/assets/45824492/858f7c50-bbfa-485f-9422-d16d461133b3">

none of which work. Is there a way to run this currently?

**Comment by rohrig** [comment]
nvm, got it 🙂 

for anyone in the future looking to do this

```bash
deno run -A jsr:@jurassicjs/create-monodeno
```

**Comment by marvinhagemeister** [comment]
Yup, the `jsr:` prefix is the way to go in Deno 👍
