### ISSUE TITLE
GitHub seems to cache badges

### ISSUE THREAD

**Issue by dsherret** [jsr-io/jsr#341]
GitHub seems to cache the badges. This currently displays as "resource not found":

https://github.com/denoland/dnt?tab=readme-ov-file#dnt---deno-to-node-transform

Using this github url: https://camo.githubusercontent.com/a3976cf1e1b6160fecf0b71b7b029413c1410ccf7d1953f92caad694cd7a77fc/68747470733a2f2f6a73722e696f2f6261646765732f4064656e6f2f646e74

Instead of using the new working: https://jsr.io/badges/@deno/dnt

**Comment by LitoMore** [comment]
It is more like a GitHub feature. You can always use a PURGE request to force update the resource.

**Comment by LitoMore** [comment]
![](https://github.com/jsr-io/jsr/assets/8186898/7c13280e-7d17-4bc6-9db7-b810e2ee1244)

This information should help.

**Comment by dahlia** [comment]
Shields.io badges have `Cache-Control`, `Expires`, and `Last-Modified` headers in their responses, whereas JSR badges don't.  This difference might be a cause.
