### ISSUE TITLE
local search broken for deepMerge

### ISSUE THREAD

**Issue by ry** [jsr-io/jsr#344]
https://jsr.io/@std/collections

<img width="369" alt="Screenshot 2024-03-31 at 10 20 17 AM" src="https://github.com/jsr-io/jsr/assets/80/41484880-1a30-4cef-906f-1eb9ff25617e">

link goes to https://jsr.io/@std/collections@0.221.0/doc&#x2F;deep-merge/~/deepMerge

**Comment by KnorpelSenf** [comment]
I cannot reproduce this

**Comment by lucacasonato** [comment]
This is working correctly now.
