### ISSUE TITLE
Redesign usage instructions box

### ISSUE THREAD

**Issue by donjo** [jsr-io/jsr#354]
![image](https://github.com/jsr-io/jsr/assets/776987/2c75f16c-05df-4fde-a79e-0410c6ce73ac)
![image](https://github.com/jsr-io/jsr/assets/776987/743462fd-e4f4-455f-acd9-c531e820344b)

In an effort to make the usage instructions box a bit more compact so it doesn't push other important content off the screen, we'd like to re-style the box to remove the tabbed interface and shrink some of the code sample boxes. No actual functionality would change with this and anything that used to render as a runtime tab would now show up as a dropdown list item.

**Comment by crowlKats** [comment]
Closing as completed
