### ISSUE TITLE
Fast check: Infer return type based on return literal

### ISSUE THREAD

**Issue by marvinhagemeister** [jsr-io/jsr#358]
We currently don't seem to infer the type from a `return` statement when it is a literal.

```ts
// Works
export const foo = () => 1

// Doesn't work
export function foo() {
    return 1
}
export const foo = () => { return 1 }
```

This was reported on discord: https://discord.com/channels/684898665143206084/1203185670508515399/1225555199364436080

**Comment by lucacasonato** [comment]
Duplicate of #365?
