### ISSUE TITLE
 /// <reference lib="deno.unstable" />  is not allowed

### ISSUE THREAD

**Issue by Octo8080X** [jsr-io/jsr#362]
I have written `/// <reference lib="deno.unstable" />` to use unstable API, but it is not allowed with the following message.

```sh
$  deno publish
Checking for slow types in the public API...
Visit https://jsr.io/auth?code=HOGE-HOGE to authorize publishing of @hoge/hoge
Waiting...
Authorization successful. Authenticated as Hoge
Publishing @hoge/hoge@x.x.x ...
error: Failed to publish @hoge/hoge@x.x.x

Caused by:
    Failed to publish @hoge/hoge at 0.1.0: Triple slash directives that modify globals (for example, '/// <reference no-default-lib="true" />' or '/// <reference lib="dom" />') are not allowed. Instead instruct the user of your package to specify these directives. file:///src/hoge.ts:1:1
```

Is it possible to allow it?

**Comment by lucacasonato** [comment]
No, because reference comments in libraries will also effect the libraries of the package that is importing yours. You should specify this lib in a `compilerOptions.lib` field in `deno.json`.

**Comment by Octo8080X** [comment]
@lucacasonato san, thanks for your response.
I understand. I will respond in the way you guided me.
