### ISSUE TITLE
Handwritten mod.d.ts file is overridden when using the JSR npm package.

### ISSUE THREAD

**Issue by wangbinyq** [jsr-io/jsr#372]
I have a handwritten mod.d.ts TypeScript definition file. However, when my package is installed via npm, the mod.d.ts file is not my custom types but a generated file based on mod.ts.

My package is [jsr/wangb__vibrato-deno](https://jsr.io/@wangb/vibrato-deno)

**Comment by lucacasonato** [comment]
I am working on a partial fix for this - you will still have to rename `mod.d.ts` to something else (`types.d.ts` for example), but if you do this, this should work later this week.

A possibly better alternative that works right now: rename `mod.ts` to `mod.js` and add a `/// <reference types="./mod.d.ts" />` to the top.
