### ISSUE TITLE
package links are bleeding to edge of window with long package name

### ISSUE THREAD

**Issue by donjo** [jsr-io/jsr#374]
<img width="389" alt="Screenshot 2024-04-10 at 10 21 09 AM" src="https://github.com/jsr-io/jsr/assets/776987/db9834b7-c5ba-4a43-ba39-3df8b47d0f82">

There should always be a bit of padding on the right hand side of this content box that mirrors the padding on the left hand side of the box meaning that some of this content may need to be truncated. I think it would probably make sense to always show the package version in this case so the truncation would apply to the package name.

**Comment by furkankly** [comment]
I worked on this before to handle this [issue](https://github.com/jsr-io/jsr/issues/145) but there seems to be an oversight on possible long package names disrupting the box layout as you pointed out. 

I think we can satisfy both this issue and the linked one by setting a max width on the version and truncating both package name and the version as in:


before             |  after
:-------------------------:|:-------------------------:
![Screenshot 2024-04-16 at 11 33 23](https://github.com/jsr-io/jsr/assets/30751755/71dfba46-9c07-4e7c-86ff-fec0a6d1213b)  |  ![Screenshot 2024-04-16 at 11 35 04](https://github.com/jsr-io/jsr/assets/30751755/9c39a56f-2eac-4e53-82b2-62505c9e69af)

I'm using `max-w-20` (80px) on the version. Wdyt?

**Comment by donjo** [comment]
That looks like a good solution to me.

**Comment by furkankly** [comment]
https://github.com/jsr-io/jsr/pull/395 should fix this.

**Comment by lucacasonato** [comment]
Fixed by https://github.com/jsr-io/jsr/pull/395
