### ISSUE TITLE
Typechecking breaks on class method with generic args

### ISSUE THREAD

**Issue by atjn** [jsr-io/jsr#376]
Hi :)

I believe I have found a very specifig bug in the JSR typechecker. If you define a class with a generic, then use the generic as the spread of arguments in a method and in an overload for the method, JSR will fail to understand the types and generate a type error.

## Minimal reproduction

Create a Deno project with two files:

`main.ts`
```ts
export class argsToArray<ARGS extends unknown[]> {
  argsToArray(..._args: ARGS): void;
  argsToArray(..._args: ARGS): void {}
}
```

`deno.json`
```json
{
  "name": "@test/test",
  "version": "0.0.1",
  "exports": {
    ".": "./main.ts"
  }
}
```

Then run:
```sh
deno publish --dry-run
```
You will see the following error:
```
error: Failed ensuring public API type output is valid.

TS2394 [ERROR]: This overload signature is not compatible with its implementation signature.
  argsToArray(..._args: ARGS): void;
  ~~~~~~~~~~~
    at file:///[...]/main.ts:2:3

TS2750 [ERROR]:     The implementation signature is declared here.
      argsToArray(param0?: any): any {
      ~~~~~~~~~~~
        at file:///[...]/main.ts:3:3
```

Notice that the implementation signature shown in the error is completely wrong. We do not have only a single parameter and it is not of type `any`.

This is on Deno 1.42.1 (latest) and JSR 0.12.1 (latest). This code runs perfectly fine on Deno and `deno lint` does not produce errors, so I am guessing that this is a bug in JSR.

This is currently blocking me from publishing my library to JSR.

**Comment by lucacasonato** [comment]
Whoops, that is indeed a bug!

**Comment by lucacasonato** [comment]
This seems to be caused by the interaction of spread + overload, not the generics. We'll fix this.

**Comment by atjn** [comment]
It is caused by all of these things. If you remove the generics, there is no type error. Also if you move the generic from the class definition to the function definition, there is no type error.

**Comment by lucacasonato** [comment]
Will go out in a canary release later today hopefully.
