### ISSUE TITLE
Hyperlinks to re-exports of other jsr modules not working

### ISSUE THREAD

**Issue by kitsonk** [jsr-io/jsr#384]
Links to other jsr repos that are then leverage in documentation are not linking properly.

For example: https://jsr.io/@oak/commons/doc/range/~/range utilises `FileInfo` from `@std/http/etag`. While the hyperlinking works in the IDE, it generates the follow URL when linking to that export: `https://%40std@http/doc/0.222.1/etag.ts/~/FileInfo` which is obviously wrong.  Like this is because it is incorrectly parsing the import specifier of `"jsr:/@std/http@0.222/etag"`.

**Comment by lucacasonato** [comment]
@crowlKats PTAL
