### ISSUE TITLE
How to create a token for publishing a new package?

### ISSUE THREAD

**Issue by timharek** [jsr-io/jsr#387]
I want to try to publish a package from a different CI-system than GH Actions and according to the docs this should be possible?

https://jsr.io/docs/api#authentication-tokens

And according to these docs I should be able to generate a token in my account setting? I don't see anything in my settings for this.
<img width="977" alt="image" src="https://github.com/jsr-io/jsr/assets/5453010/d67f3577-ac6f-4894-ad13-ddc78e590696">

Can I generate a token with a different method?

**Comment by lucacasonato** [comment]
Right now, you can not. I have opened a tracking issue and am updating the docs here: https://github.com/jsr-io/jsr/pull/394.

What CI system would you like to publish from?

**Comment by timharek** [comment]
Ah, OK – thanks for the quick reply!

I want to publish from [Sourcehut's builds](https://builds.sr.ht/). And I guess that would be possible to do with `deno publish --token<access-token-from-jsr>`?

**Comment by lucacasonato** [comment]
Yes - that will need #394 first.

**Comment by kunokareal** [comment]
as a workaround you can use the `jsrw_*` tokens for now. those are issued for the frontend and stored as a cookie, and they seem to be working fine with `--token` param. they only live for 7 days, though :c

**Comment by lucacasonato** [comment]
I am going to close this in favor of #393. I have additionally opened an issue to add documentation on how to publish from alternative CI providers, such as GitLab CI or Sourcehut:
