### ISSUE TITLE
Can't use relative imports above jsr.json location

### ISSUE THREAD

**Issue by alexgleason** [jsr-io/jsr#388]
I am doing this in `mod.ts`:

```ts
import { NostrEvent } from '../interfaces/NostrEvent.ts';
```

It fails:

![Screenshot from 2024-04-16 12-29-28](https://github.com/jsr-io/jsr/assets/3639540/14c863f0-7824-417e-bb47-90ba18bc57f6)

I am importing `../interfaces/NostrEvent.ts` while having `./jsr.json`. So the file I'm importing is above jsr.json

If I move `jsr.json` up a directory, it works. But I don't want to do that, because I'm trying to manage multiple packages in one repository, with some code copied between them. Kind of like a monorepo.

`deno publish --dry-run` doesn't complain. But the package is refused by JSR.

The package is: https://jsr.io/@nostrify/ndk (Which I finally got to work by temporarily moving `jsr.json` up one directory)

**Comment by marvinhagemeister** [comment]
Workspace support in Deno isn't ready yet. Having proper support for workspaces in Deno would resolve this. Support for workspaces is being tracked here https://github.com/denoland/deno/issues/22942

**Comment by alexgleason** [comment]
Good to know. But this problem would occur even with `~/Projects/myproj/mod.ts` importing `../otherproj/b.ts`

Importing local code from outside of the JSR working directory should work, right?

**Comment by marvinhagemeister** [comment]
Right now the assumption is that the packages `jsr.json/deno.json` is at the root of the package. Once support for workspaces land it will be possible to reference packages in other folders, but not importing files from above the package folder. It's very unlikely that we'll ever add support for that as it introduces significant complexity and edge cases during the publish process.

We haven't decided on that in the team yet, but my feeling is that we'd rather spent time working on other JSR stuff in the coming months. I wouldn't plan my code around this being supported anytime soon (if at all).

**Comment by alexgleason** [comment]
Thank you for clarifying @marvinhagemeister 

In that case I'll close this in favor of https://github.com/denoland/deno/issues/22942
