### ISSUE TITLE
Sidebar on package page is full screen height, even if this doesn't make sense

### ISSUE THREAD

**Issue by lucacasonato** [jsr-io/jsr#41]
![image](https://github.com/jsr-io/jsr/assets/7829205/f11327d5-1d9b-4563-a39e-d531460b4aad)

Here to view the bottom of the sidebar, I need to scroll the viewport (the page), and the sidebar all the way to the bottom. This makes no sense, because the page content is small enough to fit on the page without the viewport having to scroll.

The current behaviour only made sense if the content was larger than the viewport (which it is not).

**Comment by jollytoad** [comment]
This sidebar really needs to scroll independently of the main content, so far this is probably my number one bugbear with the UI atm. I tried to take a look at fixing this, but I've no idea what's going on with all the tailwind gubbins!

**Comment by yoavbls** [comment]
My PR here solves this: https://github.com/jsr-io/jsr/pull/260
Without limiting the height at all, without scrollbars and it remains sticky

**Comment by jollytoad** [comment]
The sidebar still doesn't scroll all the way to the bottom, unless you scroll the main page. You can see this behaviour here... https://jsr.io/@http/fns
