### ISSUE TITLE
Symbol Methods do not link properly...

### ISSUE THREAD

**Issue by kitsonk** [jsr-io/jsr#416]
Clicking on a link to drill into a method that is a symbol results in a 404 instead of the documentation for that method.  For example clicking on the link in this class: https://jsr.io/@oak/oak/doc/context/~/Context#method_[Symbol_for(&quot;Deno_customInspect&quot;)]_0 will lead you to https://jsr.io/@oak/oak/doc/context/~/Context.prototype.[Symbol.for(%22Deno.customInspect%22)] which is a 404 Not Found.

**Comment by lucacasonato** [comment]
It is now working!
