### ISSUE TITLE
OIDC auth support

### ISSUE THREAD

**Issue by micash545** [jsr-io/jsr#419]

**Comment by lucacasonato** [comment]
This is not actionable. Please include more details on what feature you are requesting than just a title. JSR does support OIDC auth with GitHub Actions for example: https://jsr.io/docs/publishing-packages#publishing-from-github-actions

You can open a new issue if you actually write a description.

**Comment by micash545** [comment]
I mean that other oidc providers gitea for example

**Comment by lucacasonato** [comment]
Then open a new issue that describes that. This was very unclear from this issue you opened
