### ISSUE TITLE
web ui: The user/scopes looks similar to a text field

### ISSUE THREAD

**Issue by hashrock** [jsr-io/jsr#424]
<img width="893" alt="image" src="https://github.com/jsr-io/jsr/assets/3132889/412420aa-945f-45f8-ae9c-c6a9c86e236a">

At first, I mistook this for a text field to change the scope name. This confusion might be mitigated by adding an icon.

wdty? @donjo

**Comment by donjo** [comment]
What kind of icon are you thinking about? Something we would generate a default for an let users who manage the scope define an override, like a scope profile pic? 

Another thing we could do is to show some basic metadata associated with the scope (like number of packages and members?) and maybe break it out of a simple table view

**Comment by lucacasonato** [comment]
I think maybe just toning down the border and bg color may help already? If it's less obviously distinct from the rest of the page, it won't feel like an interactive component.

**Comment by hashrock** [comment]
![CleanShot 2024-05-01 at 01 35 35@2x](https://github.com/jsr-io/jsr/assets/3132889/7e92fb1f-a364-4ccc-b67b-e022087a13d0)

I was thinking of adding a simple arrow icon. But I think it's smart to add metadata!

**Comment by alectrocute** [comment]
Resolved in https://github.com/jsr-io/jsr/pull/631 by disabling the background color if there's only one `ListPanel` child. This effectively "tones down" the background color and I feel fixes this friction point.
