### ISSUE TITLE
Newly published packages show a blank "Works with" in the header.

### ISSUE THREAD

**Issue by donjo** [jsr-io/jsr#443]
<img width="1209" alt="Screenshot 2024-04-24 at 10 01 38 AM" src="https://github.com/jsr-io/jsr/assets/776987/90824438-323e-4a7c-9d2a-12840fd36f78">

Right now when you first publish a package the runtime compatibility options are unset so the "works with" field in the package header is blank. If you go into settings it looks like they are all set to "unknown compatibility", however, the UI doesn't reflect that until you hit save for the first time. I would suggest one of the following options:

1. New packages are set to "compatibility unknown" upon publish which would render some content in the "Works with" section of the package header and the form fields on the settings page would be correct.

**or** _(if we want compatibility definition to be fully opt-in)_

2. The form fields on the settings page are set to an empty state. The "works with" section of the package header is not visibility unless at least 1 runtime compatibility (even unknown compatibility) is defined.

**Comment by alectrocute** [comment]
Addressing this in https://github.com/jsr-io/jsr/pull/627.
