### ISSUE TITLE
Add OpenSearch support

### ISSUE THREAD

**Issue by foster-hangdaan** [jsr-io/jsr#457]
This is a UX improvement which adds the ability to search JSR packages without having to navigate to jsr.io first. On Firefox, a plus icon appears on the search bar which allows the user to add jsr.io as another search engine.

npmjs.com supports this feature:

![image](https://github.com/jsr-io/jsr/assets/156146315/336b990c-79dd-4615-9e9c-8e3d443d1d9f)

jsr.io does not:

![image](https://github.com/jsr-io/jsr/assets/156146315/20ac2bde-88f0-4446-9860-872e3c931f4a)

References:

- [OpenSearch Documentation](https://github.com/dewitt/opensearch)
- [MDN: OpenSearch description format](https://developer.mozilla.org/en-US/docs/Web/OpenSearch)
- [The Chromium Project: Tab to Search](https://www.chromium.org/tab-to-search/)

**Comment by yossydev** [comment]
Hi, @foster-hangdaan 👋
Can I take up this issue?

**Comment by lucacasonato** [comment]
@yossydev Yes, absolutely!
