### ISSUE TITLE
Missing name in the default export example in the generated docs

### ISSUE THREAD

**Issue by nicolo-ribaudo** [jsr-io/jsr#459]
https://jsr.io/@nic/decimal-literal/doc/~/default

![image](https://github.com/jsr-io/jsr/assets/7000710/018d24a3-136c-4a2f-a6f5-b0622acc4368)

`import  from "name"` is missing _some_ identifier. It'd be great if I (package author) could configure it, but an auto-generated one is still better than nothing.

**Comment by kt3k** [comment]
Now we use `module` identifier for this case.

```ts
import module from "@nic/decimal-literal";
```

**Comment by kt3k** [comment]
> It'd be great if I (package author) could configure it,

It's not possible yet. Alternatively you can set arbitrary identifier if you use the following pattern:

```ts
export default function Foobar() { ... }
```

Then the usage box shows

```ts
import Foobar from "...";
```

**Comment by crowlKats** [comment]
Closing as fixed
