### ISSUE TITLE
"no documentation available" when there is indeed documentation

### ISSUE THREAD

**Issue by saolsen** [jsr-io/jsr#465]
The module page shows this.

![image](https://github.com/jsr-io/jsr/assets/508702/ae544c6c-446c-425a-a921-6d8eb04a4ae1)

But the interface is documented.

https://jsr.io/@gameplay/games/doc/poker/~/CheckAction
https://jsr.io/@gameplay/games/0.1.1/poker.ts#L740

**Comment by crowlKats** [comment]
Related issue: #454
