### ISSUE TITLE
url has "doc" but tab says "docs"

### ISSUE THREAD

**Issue by ry** [jsr-io/jsr#469]
minor nit

<img width="594" alt="Screenshot 2024-04-30 at 5 33 32 AM" src="https://github.com/jsr-io/jsr/assets/80/4506cd68-098f-4ded-a4b5-050db6c637f6">

**Comment by lucacasonato** [comment]
Not going to change this. Singular docs in the UI doesn't make sense, and changing the path will either break a bunch of URLs, or be bad for SEO because a bunch of new redirects are added.
