### ISSUE TITLE
Score for "Has docs for most symbols" is wrong when an export has overloads

### ISSUE THREAD

**Issue by lowlighter** [jsr-io/jsr#472]
If a symbol has overloads, then only the first one count as being documented so it lower the score

I've confirmed this is the case by publishing two releases of a package, one without overloads and one with them, and it changes the score.
![image](https://github.com/jsr-io/jsr/assets/22963968/07cc77b0-e31d-473a-834c-4888bfb1ad78)
![image](https://github.com/jsr-io/jsr/assets/22963968/7a28b5ae-927d-4545-9a27-3fe608fa0d5b)

This package has only one export, and with 4 overloads it reports "Currently 25% of symbols are documented.".
100/4 = 25 (this is actually how I discovered the issue)

**Comment by dsherret** [comment]
This is correct. The jsdoc only applies to the single overload and the other overloads are missing documentation as can be seen here: https://jsr.io/@libs/qrcode@1.0.3/doc/~/qrcode
