### ISSUE TITLE
web ui: renaming during deno publish UX

### ISSUE THREAD

**Issue by hashrock** [jsr-io/jsr#478]
When publishing with `deno publish`, if you rename with a text field in `Publish a package` form, The CLI becomes unable to proceed.
This is not a serious issue (UX), but it might confuse users, so it might be better to guide them in some way.

**Step 1:** 

publish `study-jsr-202305-rename` module with `deno publish`

**Step 2:**

Rename the module with `study-jsr-202305-rename-r1` on the text field

![CleanShot 2024-05-03 at 10 21 11](https://github.com/jsr-io/jsr/assets/3132889/5b272652-fd49-4e99-b42e-041cd84f172e)

**Result:**

CLI will be waiting forever

![CleanShot 2024-05-03 at 10 21 31@2x](https://github.com/jsr-io/jsr/assets/3132889/991267bc-bc48-4f63-b0b0-0c622ba83490)

**Workaround:**

Interrupt the CLI, rewrite the `name` field in `deno.json` to `study-jsr-202305-rename-r1`, and re-run `deno publish` to be able to publish.

**Comment by lucacasonato** [comment]
We should prevent you from modifying inputs if you are coming from the CLI.
