### ISSUE TITLE
add Usage instructions "import jsr:@xxx" type

### ISSUE THREAD

**Issue by fushihara** [jsr-io/jsr#482]
I would like to see a notation using JSR identifiers added to the instructions on each page.
Also, the version notation should be clearly stated.

I attach an image with the desired notation added

I think the most convenient thing about starting to use deno is that I don't have to run npm install when I use a new package.
I don't want to go back to those days of running npm install every time!

![image](https://github.com/jsr-io/jsr/assets/1039534/1321b26c-1056-4ba1-819e-05a0c25acef2)
![image](https://github.com/jsr-io/jsr/assets/1039534/c5e2c791-06dd-4f67-8bd9-2ddb56867361)

**Comment by magurotuna** [comment]
Looks like duplicate of #381?

**Comment by fushihara** [comment]
You were indeed right!
I think we can close this issue.

Thank you!
