### ISSUE TITLE
error: Script not found "jsr"

### ISSUE THREAD

**Issue by AndreaDelliGatti** [jsr-io/jsr#497]
On Windows 11 when i try to add a jsr package with the following command

```shell
bunx jsr add some-package
```

i get this error

***error: Script not found "jsr"***

instead, when I launch the bun install command and inside the package.json there are jsr packages they are installed normally.

bun version: 1.1.7

**Comment by lucacasonato** [comment]
You may want to raise an issue with Bun about this.
