### ISSUE TITLE
Search is completely broken

### ISSUE THREAD

**Issue by KnorpelSenf** [jsr-io/jsr#522]
Currently, the search feature on https://jsr.io is completely broken:
![image](https://github.com/jsr-io/jsr/assets/12952387/7785fe09-afd0-4c2d-9a23-4a7b7a499ba3)
This very same response is returned for every search query.

**Comment by marvinhagemeister** [comment]
Can't reproduce that on my end on macOS. Tested with Safari, Firefox and Chrome.

**Comment by iuioiua** [comment]
Works fine for me too.

**Comment by KnorpelSenf** [comment]
It's back for me now, too! 🎉
