### ISSUE TITLE
Jsr documentation badges are broken

### ISSUE THREAD

**Issue by Hexagon** [jsr-io/jsr#539]
"Please use https"

![Screenshot_20240520_213844_Chrome](https://github.com/jsr-io/jsr/assets/419737/fd9820aa-5254-4dff-a5c3-bbd377c43417)

I am using the markdown provided by the official docs. It seems to affect all (checked) repos.

**Comment by o-az** [comment]
same issue shows up in jsr docs: https://jsr.io/docs/badges#version-badge
![CleanShot 2024-05-20 at 17 08 25](https://github.com/jsr-io/jsr/assets/23618431/938b13e3-6189-49d4-8d2b-b4f3d530b39b)
