### ISSUE TITLE
URL in symbol description overflows container

### ISSUE THREAD

**Issue by donjo** [jsr-io/jsr#541]
Example from [`@std/fmt`](https://jsr.io/@std/fmt/doc/colors/~)

<img width="474" alt="Screenshot 2024-05-21 at 2 18 27 PM" src="https://github.com/jsr-io/jsr/assets/776987/d9414bcb-e08b-44b5-b896-4ea53e6724f9">

**Comment by 0es** [comment]
#550 a little help :)

**Comment by donjo** [comment]
fixed in #550
