### ISSUE TITLE
Why publishing tsconfig.json?

### ISSUE THREAD

**Issue by fdc-viktor-luft** [jsr-io/jsr#567]
Is there any good reason to publish the `tsconfig.json` in the package?

I used `pnpm` and `pnpm dlx jsr publish` + `pnpm dlx jsr add ...` to see that my `tsconfig.json` was published.

I could work around that issue by specifying "include" files manually, but shouldn't this be avoided by default?

**Comment by marvinhagemeister** [comment]
Merging this issue into https://github.com/jsr-io/jsr/issues/566
