### ISSUE TITLE
Why publishing `.test.ts` files?

### ISSUE THREAD

**Issue by fdc-viktor-luft** [jsr-io/jsr#568]
I think in general only those files should be published that are required by the files that are listed as "exports".

In particular I found test files to be published as well.

I used `pnpm` and `pnpm dlx jsr publish` + `pnpm dlx jsr add ...` to see that my `index.test.ts` was published.

I could work around that issue by specifying "include" files manually, but shouldn't this be avoided by default?

**Comment by marvinhagemeister** [comment]
Merging this issue into https://github.com/jsr-io/jsr/issues/566
