### ISSUE TITLE
All examples contain"-" character at "@std" are wrong

### ISSUE THREAD

**Issue by h76oeI6pMxU9g4p8aCpc6Q** [jsr-io/jsr#578]
For example (I using "jsr:" because I using Deno):

https://jsr.io/@std/assert/doc/~/assertEquals
```js
import { assertEquals } from "jsr:@std/assert/assert-equals";
```
This line of code will throw "TypeError: Unknown export" because the "assert-equals" export not exists.

The correct name is:
```js
import { assertEquals } from "jsr:@std/assert/assert_equals";
```
**Change "-" to "_"**

All other examples contain"-" character at "@std" are also wrong.

**Comment by dsherret** [comment]
@h76oeI6pMxU9g4p8aCpc6Q the latest versions use a hyphen: https://jsr.io/@std/assert@0.225.3/doc/assert-equals/~

Run with `deno run --reload ...` and you will see that `assert_equals` no longer exists.
