### ISSUE TITLE
The documentation should show the possible exceptions when available

### ISSUE THREAD

**Issue by felds** [jsr-io/jsr#597]
Currently, the generated docs only show generics, parameters and return types. Having the possible exceptions listed could be useful when using a library.

The `@throws` tag is currently badly supported but this could change if tools made any use of it.

MDN list the possible exceptions under the return types and I think it's a good standard for any documentation. Examples:

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize#exceptions
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI#exceptions

**Comment by lucacasonato** [comment]
cc @crowlKats

**Comment by crowlKats** [comment]
@throws is supported nowadays, so closing
