### ISSUE TITLE
deno deploy + jsr

### ISSUE THREAD

**Issue by irekgroup** [jsr-io/jsr#613]
When I try to deploy the repository () to the deployment deno, I always get the build error `Task not found: build.`
Are there instructions for deploying to the deposit of this repository?
![image](https://github.com/jsr-io/jsr/assets/70753735/dddebe4a-dce6-40a4-b8de-42e71a8ca908)

**Comment by lucacasonato** [comment]
JSR does not run on Deno Deploy.
