### ISSUE TITLE
Negative infinity in a type causes "Failed ensuring public API type output is valid."

### ISSUE THREAD

**Issue by m93a** [jsr-io/jsr#617]
In TypeScript, there are ways to make a numeric literal representing `Infinity` and `-Infinity`:
```ts
export type PositiveInfinity = 1e999;
export type NegativeInfinity = -1e999;
```
However, trying to publish those to JSR, `deno publish` fails with the following:
```
Checking for slow types in the public API...
error: Failed ensuring public API type output is valid.

TS1110 [ERROR]: Type expected.
export type NegativeInfinity = -Infinity;
                               ^

TS2749 [ERROR]: 'Infinity' refers to a value, but is being used as a type here. Did you mean 'typeof Infinity'?
export type PositiveInfinity = Infinity;
                               ~~~~~~~~

Found 2 errors.

You may have discovered a bug in Deno. Please open an issue at: https://github.com/denoland/deno/issues/
```
Note that the TypeScript error shows a different "source" than the actual source file.

For the PositiveInfinity, there is a way around it:
```ts
export type PositiveInfinity = typeof Infinity;
```
However, there is no similar walkaround for the NegativeInfinity type.

**Comment by lucacasonato** [comment]
That looks like a bug!

**Comment by lucacasonato** [comment]
Upstream bug in SWC: https://github.com/swc-project/swc/issues/9223

**Comment by m93a** [comment]
The bug seems to be resolved – I can't reproduce it anymore!
