### ISSUE TITLE
How are packages selected to be featured on the home page?

### ISSUE THREAD

**Issue by fabian-hiller** [jsr-io/jsr#619]
I couldn't find any information about this in the documentation. That's why I created this issue. I am interested in being featured with [Valibot](https://jsr.io/@valibot/valibot). Currently, Valibot is one of the most popular packages on [deno.land/x](https://deno.land/x).

**Comment by lucacasonato** [comment]
They are currently featured based on manual action from the moderation team. Currently we try to showcase packages with high scores. Somehow, we must have missed featuring Valibot - fixed now!
