### ISSUE TITLE
Inconsistent behavior when using `bunx jsr add` (on Windows)

### ISSUE THREAD

**Issue by yyhhenry** [jsr-io/jsr#621]
Description:
There are inconsistencies in how bun handles jsr.io packages when using `bunx jsr add` compared to other package managers like pnpm. This leads to issues with package references and update failures.
﻿
Steps to reproduce:
1. Using pnpm (baseline):
Run: `pnpm dlx jsr add @yyhhenry/rust-result` or `pnpm dlx jsr add @yyhhenry/rust-result@latest`
Result in package.json: `"@yyhhenry/rust-result": "npm:@jsr/yyhhenry__rust-result@^0.2.9"`
﻿
2. Using bun:
a. Run: `bunx jsr add @yyhhenry/rust-result`
Result in package.json: `"@yyhhenry/rust-result": "npm:@jsr/yyhhenry__rust-result"`
﻿
b. Run: `bunx jsr add @yyhhenry/rust-result@latest`
Result in package.json: `"@yyhhenry/rust-result": "^0.2.9"`
﻿
c. After step b, run: `bun update`
Error (another @yyhhenry/rust-result has been published to npmjs):
```
bun update v1.1.17 (bb66bba1)
error: No version matching "^0.2.9" found for specifier "@yyhhenry/rust-result" (but package exists)
error: @yyhhenry/rust-result@^0.2.9 failed to resolve
```
﻿

Expected behavior:
1. `bunx jsr add @yyhhenry/rust-result` should result in a package reference similar to the pnpm result, including the version number.
2. `bunx jsr add @yyhhenry/rust-result@latest` should maintain the jsr.io package reference format.
3. `bun update` should successfully update the package without errors.
﻿

Actual behavior:

1. The package reference lacks the version number.
2. The package reference is changed to a regular npm-style version number.
3. `bun update` fails due to inability to resolve the package.
﻿

Environment:

- Bun version: 1.1.17
- Operating System: Win 11
﻿

Additional information:
This inconsistency in handling jsr.io packages leads to difficulties in managing dependencies and potential build failures. It's important to align bun's behavior with other package managers or provide clear documentation on these differences.
﻿

**Comment by marvinhagemeister** [comment]
That sounds like a bug in bun's package manager code. It seems like it's not inserting the version string. The JSR CLI directly shells out to bun and follows the npm protocol to a tee. Please report this bug at the bun repo.
