### ISSUE TITLE
Failed to resolve dependencies using package.json or import_map.json

### ISSUE THREAD

**Issue by slainless** [jsr-io/jsr#634]
18 hours ago, my package deployment/publishing worked as expected, but not now.

```
Failed to publish @slainless/prodeskel-ws at 0.1.13: failed to build module graph: Module not found "file:///dist/core/typia".
```

No big commit from my end since the last successful build so it's probably from jsr.

Recent build (failed): https://github.com/slainless/prodeskel-ws/actions/runs/9789189029
Last successful build: https://github.com/slainless/prodeskel-ws/actions/runs/9777157205
Comparing both commits: https://github.com/slainless/prodeskel-ws/compare/0272ef9..4775e95

**Comment by slainless** [comment]
OK, I thought adding import_map.json might help, but nope. It still failed to resolve my dependencies.

**Comment by jpwilliams** [comment]
Also starting to see this - no changes to `jsr.json`, `package.json` (apart from the `version`!), or any strange new imports.

https://github.com/inngest/inngest-js/actions/runs/9798531607/job/27057242163

**Comment by sebastianwessel** [comment]
I'm brand new at jsr.io and tried to publish my first package, but it failed with similar error.

**Comment by marvinhagemeister** [comment]
Related https://github.com/denoland/deno/issues/24430

**Comment by marvinhagemeister** [comment]
Good news: We pushed a fix and this should be resolved now 👍
