### ISSUE TITLE
Bug: publish dosn'е work

### ISSUE THREAD

**Issue by PandaWorker** [jsr-io/jsr#643]
I want to publish the package, but the publication freezes
There are no errors in the console

https://jsr.io/@undicijs/transport/versions

<img width="663" alt="image" src="https://github.com/jsr-io/jsr/assets/57873412/e8bb67c8-f44d-4b43-9e18-1926bcdb3ae4">

**Comment by lucacasonato** [comment]
Sorry, we're working on it.

**Comment by marvinhagemeister** [comment]
Let's track this in https://github.com/jsr-io/jsr/issues/642 which is the same issue.
