### ISSUE TITLE
Provenance in REST API

### ISSUE THREAD

**Issue by adamgreg** [jsr-io/jsr#652]
Please could provenance information be included in the "Package version metadata" response of the registry API?

It would be useful for automated workflows.

**Comment by adamgreg** [comment]
For context, I need to produce an SBOM for my application. Packages in `node_modules` are picked up automatically by Anchore, but JSR packages are not, so I'd like to add a step to my CI pipeline to produce an SBOM file with a Github purl for each JSR dep.

I already have a script that does that for `deno.land/x` deps - its API includes github upload information (e.g. https://apiland.deno.dev/v2/modules/postgresjs/v3.4.4 ).

The JSR Sigstore transparency log seems ideal, but there seems to be no link to it in the JSR API response, only via the package's HTML page.

**Comment by lucacasonato** [comment]
The field `rekorLogId` in the `https://api.jsr.io/scopes/$scope/packages/$package/versions/$version` endpoint contains the ID where the provenance info for this package is stored in the public Sigstore provenance log.

For example, [@std/fs@1.0.0-rc.5](https://api.jsr.io/scopes/std/packages/fs/versions/1.0.0-rc.5) has the `rekorLogId` of `111184050`. You can find the corresponding Sigstore transparency log entry at https://search.sigstore.dev/?logIndex=111184050.

You can also download the entry programatically from the Rekor API:

```sh
curl -X 'POST' \
  'https://rekor.sigstore.dev/api/v1/log/entries/retrieve' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "logIndexes": [
    111184050
  ]
}'
```

Hope this helps!

**Comment by adamgreg** [comment]
That's extremely helpful, thanks Luca!

Sorry I didn't think to check the management API - I misread the docs and assumed it was only for authenticated users to manage their packages.
