### ISSUE TITLE
Suggestion: npm compatibility - add types to the generated package.json

### ISSUE THREAD

**Issue by lifaon74** [jsr-io/jsr#662]
Hi, i would like to report a suggestion to improve the generated `package.json` when using the [compatibility layer](https://jsr.io/docs/npm-compatibility).

When doing:

```sh
npx jsr add @std/uuid
```

I get the following `package.json`:

![image](https://github.com/user-attachments/assets/4e9dcab5-28b9-44de-a1de-4fbdd77475a5)

```json
{
  "name": "@jsr/std__uuid",
  "version": "0.213.1",
  "homepage": "https://jsr.io/@std/uuid",
  "type": "module",
  "dependencies": {
    "@jsr/std__assert": "^0.213.1",
    "@jsr/std__bytes": "^0.213.1",
    "@jsr/std__crypto": "^0.213.1"
  },
  "exports": {
    ".": "./mod.js",
    "./v1": "./v1.js",
    "./v3": "./v3.js",
    "./v4": "./v4.js",
    "./v5": "./v5.js",
    "./constants": "./constants.js"
  },
}
```

We can see that types are not exported, thus, it result in a typescript error:

![without-types](https://github.com/user-attachments/assets/8fce26c3-c13b-4d3b-b3c6-f1e7e23cd510)

Howerver, by modifiyng a little bit the `package.json` it's easy to fix this error:

```json
{
  "name": "@jsr/std__uuid",
  "version": "0.213.1",
  "homepage": "https://jsr.io/@std/uuid",
  "type": "module",
  "dependencies": {
    "@jsr/std__assert": "^0.213.1",
    "@jsr/std__bytes": "^0.213.1",
    "@jsr/std__crypto": "^0.213.1"
  },
  "exports": {
    ".": {
      "default": "./mod.js",
+      "types": "./mod.d.ts"
    },
    "./v1":{
      "default": "./v1.js",
+      "types": "./v1.d.ts"
    },
    "./v3": {
      "default": "./v3.js",
+      "types": "./v3.d.ts"
    },
    "./v4": {
      "default": "./v4.js",
+      "types": "./v4.d.ts"
    },
    "./v5": {
      "default": "./v5.js",
+      "types": "./v5.d.ts"
    },
    "./constants": "./constants.js"
  },
+  "typings": "./mod.d.ts",
+  "types": ["./mod.d.ts"]
}

```

![image](https://github.com/user-attachments/assets/73f6d25f-9656-4597-b0d3-fdab48ef658d)

So I would suggest to modify the generated `package.json` to include types, thus providing a better user experience for the devs using the compatibility layer.

While i got you, thanks for the amazing job 🎉, jsr is a true game changer !

### Environnement

Webstorm 2024.1.5
[Vite project](https://jsr.io/docs/with/vite) without deno

**Comment by lucacasonato** [comment]
You seem to have an old revision of the tarball. I suggest delete your lock file (`package-lock.json` / `yarn.lock` / `pnpm.lock`) and re-install. This will pull down a new package tarball revision where this is fixed.

**Comment by lifaon74** [comment]
You are right ! Thanks for the help. Indeed I got an old version instead of the new one :+1:
