### ISSUE TITLE
error: Invalid package specifier 'jsr:@gramio/core@>=0.0.39 <1.0.0'

### ISSUE THREAD

**Issue by kravetsone** [jsr-io/jsr#671]
https://jsr.io/docs/native-imports#installing-and-importing-jsr-packages

```bash
error: Invalid package specifier 'jsr:@gramio/core@>=0.0.39 <1.0.0'. Invalid version requirement. Invalid specifier version requirement. Unexpected character.
  >=0.0.39 <1.0.0
```

In Github Action - https://github.com/gramiojs/prompt/actions/runs/10130934955/job/28012958923

![image](https://github.com/user-attachments/assets/a534a751-aca9-4cb7-af61-e66cb28afb7e)

But it should works fine - https://jubianchi.github.io/semver-check/#/%3E%3D0.0.39%20%3C%201.0.0/0.1.40

**Comment by lucacasonato** [comment]
This is now fixed.

**Comment by kravetsone** [comment]
Does this really fixed?

https://github.com/gramiojs/auto-answer-callback-query/actions/runs/12092058571/job/33721300502#step:9:9

```sh
Run deno publish --allow-dirty --unstable-sloppy-imports --allow-slow-types
error: Invalid package specifier 'jsr:@gramio/core@>=0.0.39 <1.0.0'. Invalid version requirement. Invalid specifier version requirement. Unexpected character.
  >=0.0.39 <1.0.0
  ~
    at file:///home/runner/work/auto-answer-callback-query/auto-answer-callback-query/src/index.ts:10:[8](https://github.com/gramiojs/auto-answer-callback-query/actions/runs/12092058571/job/33721300502#step:9:9)
Error: Process completed with exit code 1.
```
