### ISSUE TITLE
Annoying thin line around score ring

### ISSUE THREAD

**Issue by crowlKats** [jsr-io/jsr#68]
<img width="162" alt="Screenshot 2024-02-29 at 17 25 10" src="https://github.com/jsr-io/jsr/assets/13135287/4d0163c2-fff2-47ee-a66d-406845faef12">
<img width="334" alt="Screenshot 2024-02-29 at 17 25 52" src="https://github.com/jsr-io/jsr/assets/13135287/b2ca7b6c-0649-415c-a353-60d6b29140d0">

**Comment by donjo** [comment]
are you still seeing this after some more recent updates? if so, which browser/os?

**Comment by crowlKats** [comment]
@donjo FF 123.0 on MacOS.

its quite a lot harder to see now with the gray background for the ring, so i dont think this is a concern anymore, you need to look for it to see it now.

**Comment by lucacasonato** [comment]
I don't see this anymore.
