### ISSUE TITLE
404 https://jsr.io/@std/fmt/doc/colors

### ISSUE THREAD

**Issue by ry** [jsr-io/jsr#683]
https://jsr.io/@std/fmt/doc/colors

<img width="993" alt="Screenshot 2024-08-09 at 11 49 13 AM" src="https://github.com/user-attachments/assets/b2bf8d0a-f947-4320-ae1c-c1a2d149d84f">

rendered correctly at https://jsr.io/@std/fmt/doc/colors/~

twitter improperly links https://x.com/iMalignus/status/1821934717232386551

**Comment by crowlKats** [comment]
This has been fixed
