### ISSUE TITLE
Local frontend setup error.

### ISSUE THREAD

**Issue by raashidanwar** [jsr-io/jsr#693]
I followed the steps to run the frontend locally connected with production but when I ran the command `deno task prod:frontend` I get 
```
error: Import 'https://registry-staging.deno.com/@luca/esbuild-deno-loader/meta.json' failed: error sending request for URL
(https://registry-staging.deno.com/@luca/esbuild-deno-loader/meta.json): error trying to connect: dns error: failed to lookup 
address information: nodename nor servname provided, or not known at https://deno.land/x/fresh@1.6.6/src/build/deps.ts:9:29
```

**Comment by marvinhagemeister** [comment]
Upgrade your deno version to resolve this error. The `registry-staging.deno.com` domain was our domain at the end of 2023 before it later became JSR.

**Comment by lucacasonato** [comment]
Closing as @marvinhagemeister presented the solution.
