### ISSUE TITLE
SVG images in readme are broken

### ISSUE THREAD

**Issue by kidonng** [jsr-io/jsr#707]
Example: https://jsr.io/@david/dax

<img width="229" alt="Screenshot 2024-09-01 at 4 48 02 PM" src="https://github.com/user-attachments/assets/e6c39bc4-d504-4336-989b-0a06119caa1c">

It seems SVG files are directly served from Google storage with wrong `content-type` header:

```shellsession
$ curl -i https://jsr.io/@david/dax/0.41.0/src/assets/logo.svg
HTTP/2 200
...ısnip...
content-type: application/octet-stream
server: UploadServer
via: 1.1 google
...snip...

<svg width="351" height="240" viewBox="0 0 351 240" fill="none" xmlns="http://www.w3.org/2000/svg">
```

I looked at [the corresponding frontend route](https://github.com/jsr-io/jsr/blob/af352dfb206218b4ec1305ed42c09c45785bd2d6/frontend/routes/package/source.tsx) but unfortunately had no idea how this (should be) handled.

**Comment by lucacasonato** [comment]
This is fixed now
