### ISSUE TITLE
Search in JSR Docs is not working at all

### ISSUE THREAD

**Issue by yuhr** [jsr-io/jsr#716]
In the “Search for documentation” field, typing anything just shows nothing but `...` in the candidates popup.

<img width="694" alt="Screenshot 2024-09-10 at 5 41 50" src="https://github.com/user-attachments/assets/525e4bc5-20f7-42f0-8908-50441b7c66e0">

Getting multiple errors in the inspector console:

<img width="915" alt="Screenshot 2024-09-10 at 5 43 06" src="https://github.com/user-attachments/assets/871b0129-3ec3-4d76-9831-5953d367d151">

Tested on the latest Chrome and Safari.

**Comment by crowlKats** [comment]
Closing as this was fixed
