### ISSUE TITLE
ux: no reaction when you clicked the copy icon.

### ISSUE THREAD

**Issue by familyboat** [jsr-io/jsr#730]
When i click the copy button, i should get some reaction, like `Copied that`. No reaction makes me annoying😞.
![IMG_20240917_222621](https://github.com/user-attachments/assets/9c3a0c0a-9237-4d66-bd18-72ac788934ec)

**Comment by mbhrznr** [comment]
@lucacasonato could this be an upstream issue in https://github.com/denoland/deno_doc?
started to do some digging, looks like the button is provided by `UsageComposerEntry`.

**Comment by lucacasonato** [comment]
Yes, that is possible
