### ISSUE TITLE
Doc overview is missing white-spaces where line breaks are

### ISSUE THREAD

**Issue by bodograumann** [jsr-io/jsr#737]
In the generated docs there should be a white-space, were the source comment contains a line-break.
This is only broken in the overview page, but not in the details page of a symbol.

For example https://jsr.io/@std/random/doc says `[…]anoption may be customized by passing a[…]`, while https://jsr.io/@std/random/doc/~/Prng correctly says `[…]an option may be customized by passing a[…]`.
This seems to happen everewhere, but many doc comments don't contain multiple lines.

**Comment by homersimpsons** [comment]
Another one from https://jsr.io/@std/testing/doc:

> A [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development) interfaceto Deno.test() API.

The sources contain a line break https://github.com/denoland/std/blob/ed79df4696e2e2522e08a18a5d4efb98b7de762d/testing/bdd.ts#L4-L5
