### ISSUE TITLE
[ BUG ] Incorrect GitHub Link Redirect on User Profiles

### ISSUE THREAD

**Issue by mikoloism** [jsr-io/jsr#761]
When clicking on the GitHub link on a user's profile on jsr.io, the link redirects to an `undefined` username on GitHub instead of the actual username of the users. This problem occurs continuously in different user profiles.

![image](https://github.com/user-attachments/assets/cbb7b667-d7ac-4753-9a2b-a236da6060bc)
![image](https://github.com/user-attachments/assets/57261d63-9e70-47fa-9a04-28014a209094)

**Comment by akmittal** [comment]
Its working as expected for me 
![Screenshot 2024-10-25 at 11 11 53 PM](https://github.com/user-attachments/assets/ae1037cb-e973-46bc-8f35-7d63b5144087)

**Comment by mikoloism** [comment]
Hello Dear @akmittal. Can I request that you do a test on [the scope db members](https://jsr.io/@db/~/members) and then we can check the result?

**Comment by akmittal** [comment]
@mikoloism All those are working for me too. Can you try in a different browser or clear browser cache and try
![Screenshot 2024-10-26 at 9 20 17 AM](https://github.com/user-attachments/assets/0e08ea41-7b36-4a99-b472-15339cdba161)

**Comment by mikoloism** [comment]
Yes, Your are correct. thank!
