### ISSUE TITLE
Install options not appearing despite Runtime Compat being set

### ISSUE THREAD

**Issue by marvinhagemeister** [jsr-io/jsr#770]
### Discussed in https://github.com/jsr-io/jsr/discussions/769

<div type='discussions-op-text'>

<sup>Originally posted by **DeepDoge** October 18, 2024</sup>
I noticed that the install options section isn't showing up on my package page: https://jsr.io/@nomadshiba/typed-contracts
I’ve made sure the "Runtime Compat" setting is set, but i can't figure out what might be causing the issue.
I’ve checked the docs but couldn’t find anything related.  

I have another package under a different scope where it works just fine.</div>

**Comment by lucacasonato** [comment]
They are not appearing because there is no "default" (`"exports" { ".": "..." }`) entrypoint for the package. If you click into a specific symbol you can see the installation steps.

@DeepDoge

**Comment by DeepDoge** [comment]
@lucacasonato works.
