### ISSUE TITLE
jsr doesn't generate correct dts file when using the deno package as dependency in npm package

### ISSUE THREAD

**Issue by vighnesh153** [jsr-io/jsr#773]
I have a deno package that I want to use in my npm package. On jsr documentation, it shows that if I run the following command, it will install the deno pkg from jsr into my current node package:

```sh
npx jsr add @scope/pkg-name
```

Behind the scenes, when using a typescript package from JSR, it generates the javascript and dts files so that it can be consumed in npm without any bundling step. 

There happens to be an issue in the dts file generation. When I have 2 typescript files, one exporting members of another, in my original deno package, the generated dts file has references to javascript files instead of other dts files.

Example: I have the following package

```
deno-pkg
    add.ts
    mod.ts
    deno.json
```

add.ts:
```ts
/**
 * Adds the given list of numbers
 *
 * @param numbers list of numbers to add
 * @returns sum of the given numbers
 */
export function add(...numbers: number[]): number {
  return numbers.reduce((acc, curr) => acc + curr, 0);
}
```

mod.ts:
```ts
export * from "./add.ts";
```

And deno.json:
```json
{
  "name": "@vighnesh153-lab/dts-node-repro",
  "version": "0.1.2",
  "exports": "./mod.ts",
  "license": "MIT"
}
```

After publishing the above package to deno, I pulled it in my npm package using the following command:

```sh
npx jsr add @vighnesh153-lab/dts-node-repro
```

It correctly added the package as dependency to my npm package. But, typescript intellisense wasn't working. So, I investigated the `node_modules` directory to see the contents of the package. I found the following in the dependency's `package.json`:

```jsonc
{
    //...
    "exports": {
        ".": {
            "types": "./_dist/mod.d.ts",
            "default": "./mod.js"
        }
    },
    //...
}
```

As you can see, the `types` export points to the `./_dist/mod.d.ts` file which looks correct. Following is the folder structure of the dependency in `node_modules`.

<img width="361" alt="Screenshot 2024-10-20 at 3 24 51 PM" src="https://github.com/user-attachments/assets/c73e789a-52c5-44ee-b957-c4a3ecfe24b2">

When I open the `./_dist/mod.d.ts`, I see the following:

```ts
export * from "./add.js";
//# sourceMappingURL=mod.d.ts.map
```

This is incorrect because it should be exporting from the `add.d.ts` file instead of exporting `./add.js` file. 

Because of the above behaviour, the typescript intellisense isn't working in npm package.

**Comment by lucacasonato** [comment]
The generated `.d.ts` is actually correct. TypeScript unfortunately requires that you do not directly reference `.d.ts` files in import specifiers (even inside of `.d.ts` files). You instead have to reference them with `.js` files, even if the file does not exist.

As you can see here, it is working for me in VS Code:

![image](https://github.com/user-attachments/assets/e370fc54-8a71-4853-9762-0481893d821c)

What `tsconfig.json` are you using? Maybe that can help narrow down why it is not working.

**Comment by vighnesh153** [comment]
Thank you for the response. I didn't know about that typescript requirement. 

It seems I was mistaken about the impact of the `moduleResolution` setting in `tsconfig.compilerOptions`. Despite experimenting with different values earlier, I'm now **unable** to reproduce the issue. I apologize for any confusion caused.

I will close this issue. Thanks again for confirming.
