### ISSUE TITLE
`import * as` module name is a little strange

### ISSUE THREAD

**Issue by ryuapp** [jsr-io/jsr#794]
Previously `import * as mod from ...` was used, but now the example name looks a little strange.
Libraries with long names seem to cause problems like #790.

![image](https://github.com/user-attachments/assets/307bc0ba-b903-4fe4-8bc8-eeac76fbcb39)

**Comment by c43721** [comment]
this also has a side effect of turning numbers into underscores which I reported separately https://github.com/jsr-io/jsr/issues/803
