### ISSUE TITLE
Copy button is hidden when mouse approaches it

### ISSUE THREAD

**Issue by ooker777** [jsr-io/jsr#826]
![](https://i.imgur.com/05Lp0sh.gif)

**Comment by gioboa** [comment]
Can you assign this to me?

**Comment by ooker777** [comment]
how can I do that? Why can't you do that yourself?

**Comment by gioboa** [comment]
> how can I do that? Why can't you do that yourself?

No problem, I created the PR 😉 let's wait for the review
