### ISSUE TITLE
docs: add support for getters (and setters) on class

### ISSUE THREAD

**Issue by vintheweirdass** [jsr-io/jsr#833]
On our package https://jsr.io/@dunno/jsr-registry-bindings (specifically on the main file https://github.com/teamdunno/jsr-registry-bindings/blob/main/mod.ts#L155), the getters that I coded here
![image](https://github.com/user-attachments/assets/8f54b96c-5d20-4401-ac8d-f628208a3a70)
doesn't get displayed on the docs, only shows the private variables that I used for the getters
![image](https://github.com/user-attachments/assets/f9d331c4-ce63-495e-8f47-1f9cd24cccef)
But on vscode (or any other ide), the getters showed up
![image](https://github.com/user-attachments/assets/99811934-1ed4-443a-9947-5c69cac2158f)
![image](https://github.com/user-attachments/assets/50d38346-1ead-409e-8ac7-b6dbc2014fa1)
![image](https://github.com/user-attachments/assets/de36cf20-f2c3-482c-8783-191b3251d9b1)

**Comment by lucacasonato** [comment]
I can see the getter as an readonly property here: https://jsr.io/@dunno/jsr-registry-bindings/doc/~/Package#accessor_firstfetch

This page however lists the getter as a method: https://jsr.io/@dunno/jsr-registry-bindings/doc/~/Package.prototype.firstFetch. This is a bug, and is tracked here: https://github.com/denoland/deno_doc/issues/666

**Comment by vintheweirdass** [comment]
Alright thanks! Im going to close this issue for now

**Comment by vintheweirdass** [comment]
(For future readers) The bug is being tracked here => https://github.com/denoland/deno_doc/issues/666
